happy-geeks/geeks-core-library

GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

The no-image functionality didn't work properly because it never looked
for a no-image if no record of an image was found for the current
request.

Fixed no-image functionality

---

GeeksCoreLibrary/Modules/DataSelector/Services/DataSelectorsService.cs

Query built with an aggregation function didn't work anymore.

Fixed data selector aggregation function

---

GeeksCoreLibrary/Components/DataSelectorParser/DataSelectorParser.cs
GeeksCoreLibrary/Components/DataSelectorParser/Interfaces/IDataSelectorParsersService.cs
GeeksCoreLibrary/Components/DataSelectorParser/Models/DataSelectorParserCmsSettingsModel.cs
GeeksCoreLibrary/Components/DataSelectorParser/Services/CachedDataSelectorParsersService.cs
GeeksCoreLibrary/Components/DataSelectorParser/Services/DataSelectorParsersService.cs
GeeksCoreLibrary/Core/Enums/CacheAreas.cs
GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/Core/Models/GclSettings.cs
GeeksCoreLibrary/Modules/DataSelector/Services/DataSelectorsService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

The DataSelectorParser can retrieve the results of a data selector which
can then be parsed to create, for example, an HTML result based on the
retrieved data.

Added DataSelectorParser component

---

GeeksCoreLibrary/Components/Filter/Filter.cs
GeeksCoreLibrary/Components/Filter/Models/FilterCmsSettingsModel.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

- Query parameters in include block are now available in dynamic-content;
- Filter component shows all fields;
- Added "group" replacement for filter items.

Fixed multiple bugs for dynamic-content.

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Unknown variables are now removed before evaluation of the logic snippets to allow checks on empty data.

Changed order of replacements.

---

GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

Various routes would return a 404 due to a missing field in the query
that retrieves the image or file. This PR fixes that.

Fixed some issues in ItemFilesService

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/Filter/Filter.cs
GeeksCoreLibrary/Components/Repeater/Repeater.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Components and services now concatenate HTML using the StringBuilder's
Append function instead of AppendLine so no unnecessary newlines are
added.

HTML concatenation changed

---

GeeksCoreLibrary/Modules/Payments/Services/PaymentsService.cs

https://app.asana.com/0/1198919095604398/1201741833042064

get customer basket email instead of the  linked user email address

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs

Some improvements for the shopping basket for adding items.

Shopping basket improvements

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/DataSelectorParser/DataSelectorParser.cs
GeeksCoreLibrary/Components/Filter/Filter.cs
GeeksCoreLibrary/Components/Pagination/Pagination.cs
GeeksCoreLibrary/Components/Repeater/Repeater.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs
GeeksCoreLibrary/Components/WebForm/WebForm.cs
GeeksCoreLibrary/Components/WebPage/WebPage.cs
GeeksCoreLibrary/Modules/Templates/Models/DynamicContent.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

The component mode of the dynamic content blocks are now properly set.
However, the Repeater and Configurator components are exceptions as they
work with a legacy mode instead.

Fixed dynamic content component mode

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/AddToShoppingBasketModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs
GeeksCoreLibrary/Modules/Payments/Services/PaymentsService.cs

Various fixes and improvements for the shopping basket, mainly for
adding items and rendering the basket.

Shopping basket fixes

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/DataSelectorParser/DataSelectorParser.cs
GeeksCoreLibrary/Components/Filter/Filter.cs
GeeksCoreLibrary/Components/Pagination/Pagination.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs
GeeksCoreLibrary/Components/WebForm/WebForm.cs
GeeksCoreLibrary/Components/WebPage/WebPage.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs

The component mode would not always correctly be set, and the forced
component mode did not work anymore.

Fixed some issues with setting component mode

---

GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketChangeQuantitySettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketClearSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketCmsSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketLegacySettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketRemoveItemsSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketRenderSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Core/Interfaces/IWiserItemsService.cs
GeeksCoreLibrary/Core/Services/CachedWiserItemsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Various shopping basket issues related to removing items and updating quantities have been fixed.

Fixed various shopping basket issues

---

GeeksCoreLibrary/Components/Configurator/Services/CachedConfiguratorsService.cs

https://app.asana.com/0/1167986948634679/1201859104561923

adding hostname to cache key for configurator

---

GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

The MySqlDatabaseConnection now logs queries that are executed.

Added logging to MySqlDatabaseConnection

---

GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

[Image tag kunnen toevoegen in templates in Wiser](https://app.asana.com/0/1200346761113317/1200837074251362)

Various improvements and bugfixes for image templating function

---

GeeksCoreLibrary/Components/Repeater/Repeater.cs

The BetweenItemsTemplate value didn't get replacements in the MultiLayer mode.

Fixed Repeater BetweenItemsTemplate replacements

---

GeeksCoreLibrary/Components/Filter/Filter.cs
GeeksCoreLibrary/Components/WebPage/WebPage.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

- Added JOIN for parent on include with parent;
- Fix replacements in webpage component;
- Fix replacements in filters.

Fix bugs with webpages.

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Core/Interfaces/IWiserItemsService.cs
GeeksCoreLibrary/Core/Services/CachedWiserItemsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Fixed some issues with starting transactions in the shopping baskets service.

Fixed transaction issues in shopping basket

---

GeeksCoreLibrary/Components/Repeater/Repeater.cs

The "loadUptoPageNumberOverrule" did not work correctly in most cases.

Fixed some "load up to page number" issues

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

Fixed retrieving account data when account entities have their own table.

Fixed account issue in ShoppingBasketsService

---

GeeksCoreLibrary/Core/Helpers/FileSystemHelpers.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Updated image templating in the LegacyTemplatesService which was never updated. Added replacement for the image type for the fallback image so supports types beside "image/jpeg".

Image templating fixes

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Some functions no longer skip query cache as it's data that rarely changes.

WiserItemsService caching changes

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/AddToShoppingBasketModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/Constants.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketAddCouponSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketChangeQuantitySettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketClearSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketCmsSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketLegacySettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketRemoveItemsSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketRenderSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketUpdateItemSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/UpdateQuantityModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs
GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs

- Added "AddCoupon" component mode.
- Fixed various issues with coupons.
- Cleaned up some code.
- Removed BasketEntityName and BasketLineEntityName from settings. The types are always "basket" and "basketline" now.
- Changed quantity fields to Int32 instead of Decimal.
- Moved various default values to the Constants class.
- Updated the main JavaScript to include a default coupon script.

Various shopping basket component changes

---

GeeksCoreLibrary/Core/Enums/WiserItemPropertyAggregateMethods.cs
GeeksCoreLibrary/Core/Interfaces/IWiserItemsService.cs
GeeksCoreLibrary/Core/Models/EntitySettingsModel.cs
GeeksCoreLibrary/Core/Models/WiserItemPropertyAggregateMethodModel.cs
GeeksCoreLibrary/Core/Models/WiserItemPropertyAggregateOptionsModel.cs
GeeksCoreLibrary/Core/Services/CachedWiserItemsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/GeeksCoreLibrary.csproj
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

Added functionality for automatically saving items in aggregation tables, based on settings in `wiser_entityproperty`.

Item aggregation

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/Configurator/Interfaces/IConfiguratorsService.cs
GeeksCoreLibrary/Components/Configurator/Services/CachedConfiguratorsService.cs
GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs

This fixes several sproblems that were caused by my security changes from a while ago.

Bug fixes for configurator

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Templates/Enums/TemplateTypes.cs

Adds the "Routine" template type to the TemplateTypes enum and adds extra fields to the wiser_template table that are needed for routine templates.

Support for "Routine" templates for Wiser 3

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/Constants.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

Fixed coupons not getting recalculated after changes in the basket.

Fixed some issues with coupons

---

GeeksCoreLibrary/Components/OrderProcess/Controllers/OrderProcessesController.cs
GeeksCoreLibrary/Components/WebPage/Controllers/WebPageController.cs
GeeksCoreLibrary/Core/Interfaces/IWiserItemsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs

In the JCL and Wiser 2 we had functionality for putting dynamic entity blocks on a page. This functionality has now been converted to Wiser 3 / GCL.

Added functionality for entity blocks

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

Field is used by Wiser for (S)CSS and JS templates.

Added "disable_minifier" field to wiser_template

---

GeeksCoreLibrary/Modules/DataSelector/Interfaces/IDataSelectorsService.cs
GeeksCoreLibrary/Modules/DataSelector/Services/DataSelectorsService.cs

https://app.asana.com/0/1201027711166952/1201422461305695
Together with: https://github.com/happy-geeks/wiser/pull/64

Allow secure dataselectors to be loaded insecure from a secure location.

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

Coupons now get removed if the total price of the products reaches 0 (excluding any discounts).

Fixed an issue with coupons

---

GeeksCoreLibrary/Components/Account/Account.cs

Fixed some issues that prevented Wiser logins from working.

Account - Fixed Wiser login not working

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Templates/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/IPagesService.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Models/Template.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs

Adds support for global headers and footers that are set as headers/footers in the template module. The older method, via system objects, is also supported, but only if no headers and/or footers are set via the templates module.

Added support for template headers and footers

---

GeeksCoreLibrary/Components/Filter/Services/FiltersService.cs

Reverts happy-geeks/geeks-core-library#142

Revert "bugfix/filter-query"

---

GeeksCoreLibrary/Modules/Templates/Models/PageJavascriptModel.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs
GeeksCoreLibrary/Modules/Templates/Views/Shared/Template.cshtml

TrackJS can now be enabled through system objects.
https://app.asana.com/0/1200346761113317/1202486120320621

Added TrackJS plugin support

---

GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs

https://app.asana.com/0/1200896832146623/1202604143363569

Allow replacements in the checkout with specific link type.

---

GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs

The "From" string now contains the sender name if it's known.
https://app.asana.com/0/1200346761113317/1202635500636783

Updated "From" string for SMTPeter REST API

---

GeeksCoreLibrary/Modules/ItemFiles/Controllers/ItemFilesController.cs

Added range to ItemFiles routes so the url can contain either wiser1 / 2 or 3
[Asana task](https://app.asana.com/0/1201027711166952/1202666985299725/f)

Changed ItemFiles url to allow different wiser versions

---

GeeksCoreLibrary/Components/Pagination/Models/PaginationCmsSettingsModel.cs
GeeksCoreLibrary/Components/Pagination/Models/PaginationNormalSettingsModel.cs
GeeksCoreLibrary/Components/Pagination/Pagination.cs

Improved some default values and descriptions for the Pagination component.
https://app.asana.com/0/1201027711166952/1202879712279703

Pagination component defaults and descriptions

---

GeeksCoreLibrary/Components/Configurator/Interfaces/IConfiguratorsService.cs
GeeksCoreLibrary/Components/Configurator/Models/ConfigurationsModel.cs
GeeksCoreLibrary/Components/Configurator/Services/CachedConfiguratorsService.cs
GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs

This comes together with these PRs: https://github.com/happy-geeks/IntergammaLibrary/pull/11 and https://github.com/happy-geeks/JJL/pull/12
And this Asana task: [UI 8: Gescheiden producten toevoegen aan winkelmand (bijv. trekstang en gordijn)](https://app.asana.com/0/1200923549887805/1202488502041212)

Configurator - Added functionality for adding a parent to a configuration when it's being saved.

---

GeeksCoreLibrary/Components/Repeater/Repeater.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs

This extra data is used by includes and data attribute in the HTML, to send parameters to a component.
Asana task: https://app.asana.com/0/1201027711166952/1202879712279680

Fixed problems that extra data in dynamic contents did not always work properly.

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

The question has to come after the colon, otherwise errors would occur.
https://app.asana.com/0/1201394730777422/1203179783567769

Fixed an issue with default values

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs

[Configurator substap herlaadt niet altijd als gekoppelde substap verandert](https://app.asana.com/0/1200346761113317/1203181157303933)

Fixed problem that dependencies on substeps did not work.

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs

- Add option to make the images absolute to load from an external website;
- Add option to remove URL from icons loaded by xlink to load from an external website;
- Fix regex to determine xlink icons URLs causing to much selected and removed.
https://app.asana.com/0/1200923549887805/1203089809483831

Prepare configurator for XHR loaded calls.

---

GeeksCoreLibrary/Core/Models/WiserItemFileExtraDataModel.cs
GeeksCoreLibrary/Core/Models/WiserItemFileModel.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

This is made so that we can use different alt texts per language per image on a website. But it can also be used for other things in the future.
Asana ticket: https://app.asana.com/0/1201027711166952/1202813905771955
Corresponding Wiser PR: https://github.com/happy-geeks/wiser/pull/181

Item files can now have extra data

---

GeeksCoreLibrary/Core/Interfaces/IWiserItemsService.cs
GeeksCoreLibrary/Core/Services/CachedWiserItemsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/DataSelector/Interfaces/IDataSelectorsService.cs
GeeksCoreLibrary/Modules/DataSelector/Services/DataSelectorsService.cs

Combined with: https://github.com/happy-geeks/wiser/pull/178
https://app.asana.com/0/1201027711166952/1203114958448432

Add permissions for the data selectors for external API calls.

---

GeeksCoreLibrary/Components/OrderProcess/Enums/OrderProcessBasketToConceptOrderMethods.cs
GeeksCoreLibrary/Components/OrderProcess/Models/Constants.cs
GeeksCoreLibrary/Components/OrderProcess/Models/OrderProcessSettingsModel.cs
GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/Constants.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs

You can now choose whether the order process should create a copy of the basket and convert that into a concept order, or if it should directly convert a basket into a concept order. The first option is the default.
Asana: https://app.asana.com/0/29553867016121/1202986143309055

Added option for how to make a concept order from a basket.

---

GeeksCoreLibrary/Modules/ItemFiles/Controllers/ItemFilesController.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/CachedItemFilesService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

No specific Asana ticket for this, I added it because it was recently added to the JCL, for this ticket: https://app.asana.com/0/29553867016121/1202986143309055

Added possibility for loading images and files from dedicated tables (such as product_wiser_itemfile for example).

---

GeeksCoreLibrary/Modules/Templates/Controllers/CssController.cs
GeeksCoreLibrary/Modules/Templates/Controllers/JavascriptController.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Models/PageCssModel.cs
GeeksCoreLibrary/Modules/Templates/Models/PageJavascriptModel.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Views/Shared/Template.cshtml

The general CSS and JS templates now support the different insert modes as well, allowing separate general scripts and stylesheets to load in the body.
Asana: https://app.asana.com/0/1200346761113317/1201399305465281

Support for the insert mode for general templates

---

GeeksCoreLibrary/Components/OrderProcess/Middlewares/RewriteUrlToOrderProcessMiddleware.cs
GeeksCoreLibrary/Components/WebPage/Middlewares/RewriteUrlToWebPageMiddleware.cs
GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs
GeeksCoreLibrary/Modules/ItemFiles/Controllers/ItemFilesController.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs
GeeksCoreLibrary/Modules/ItemFiles/WiserItemFilesMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/RewriteUrlToTemplateMiddleware.cs

Added a middleware for loading images, so that the controller no longer needs so many routes.
It is possible to use a regex in a route, but only per segment, not the entire URL, which made it impossible to create a proper route with lots of optional segements.
Also made it possible to load images with less segments in the URL.
https://app.asana.com/0/1201027711166952/1202945204173861

Improvements for loading files

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/WiserDashboard/Models/Service.cs

Template ID is stored with the WTS service to support opening it in Wiser to edit.
https://app.asana.com/0/1200896832146623/1203098343839938

Add template ID to WTS service information.

---

GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs

https://app.asana.com/0/1201027711166952/1203156874001254

All TemplatesController functions will now return the exception properly, if an exception occurred, instead of just showing a blank page.

---

GeeksCoreLibrary/Core/Cms/CmsSettings.cs
GeeksCoreLibrary/Modules/Templates/Enums/TemplateCachingModes.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/OutputCachingMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Asana: https://app.asana.com/0/1201027711166952/1201977750164602
This also needs a PR from Wiser: https://github.com/happy-geeks/wiser/pull/203

Added functionality for caching templates and components based on an URL regex.

---

GeeksCoreLibrary/Core/Extensions/StringExtensions.cs
GeeksCoreLibrary/Core/Services/CacheService.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/OutputCachingMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Models/Constants.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs

Asana ticket: https://app.asana.com/0/1200346761113317/1202147504160717

Cached HTML files will now be divided into sub directories so that we no longer have one directory with possibly thousands of files on big websites.

---

GeeksCoreLibrary/Core/Models/WiserTableNames.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Models/Template.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Added logging to templates and components to log when they are rendered, how often they are rendered and how long it takes each time to render them.
Asana ticket: https://app.asana.com/0/1201027711166952/1203341672040181

Logging render times of components and templates

---

GeeksCoreLibrary/Components/OrderProcess/Middlewares/RewriteUrlToOrderProcessMiddleware.cs
GeeksCoreLibrary/Components/WebPage/Middlewares/RewriteUrlToWebPageMiddleware.cs
GeeksCoreLibrary/Core/Middlewares/AddAntiForgeryMiddleware.cs
GeeksCoreLibrary/Core/Middlewares/ClearCacheMiddleware.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Core/Views/Shared/_Layout.cshtml
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/ItemFiles/WiserItemFilesMiddleware.cs
GeeksCoreLibrary/Modules/Languages/Middlewares/LanguagesMiddleware.cs
GeeksCoreLibrary/Modules/Redirect/Middlewares/RedirectMiddleWare.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Enums/PageWidgetLocations.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/IPagesService.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/OutputCachingMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/RewriteUrlToTemplateMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Models/Constants.cs
GeeksCoreLibrary/Modules/Templates/Models/PageWidgetModel.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs
GeeksCoreLibrary/Modules/Templates/ViewModels/PageViewModel.cs
GeeksCoreLibrary/Modules/Templates/Views/Shared/Template.cshtml

This can be used to add custom HTML/javascript/CSS to pages on a website.
Asana ticket: https://app.asana.com/0/1201027711166952/1203511426658195
Corresponding Wiser PR: https://github.com/happy-geeks/wiser/pull/220

Added functionality for custom widgets

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs

* The `coupon_discount_X` details now get removed from basket lines when a coupon is removed.
* When a coupon is successfully added, a few extra replacements can be used in the HTML template.

Fixed some "coupon divided discount" issues

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs
GeeksCoreLibrary/Components/OrderProcess/Middlewares/RewriteUrlToOrderProcessMiddleware.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/WebForm/WebForm.cs
GeeksCoreLibrary/Components/WebPage/Middlewares/RewriteUrlToWebPageMiddleware.cs
GeeksCoreLibrary/Core/Cms/CmsComponent.cs
GeeksCoreLibrary/Core/Extensions/StringExtensions.cs
GeeksCoreLibrary/Core/Helpers/CssHelpers.cs
GeeksCoreLibrary/Core/Helpers/DatabaseHelpers.cs
GeeksCoreLibrary/Core/Helpers/StringHelpers.cs
GeeksCoreLibrary/Modules/GclReplacements/Extensions/StringReplacementsExtensions.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs
GeeksCoreLibrary/Modules/Languages/Middlewares/LanguagesMiddleware.cs
GeeksCoreLibrary/Modules/Redirect/Middlewares/RedirectMiddleWare.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/RewriteUrlToTemplateMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Also added IgnoreCase and Compiled flags to most of them to make them run faster.
No Asana ticket for this.

Added timeouts to all regexes so that they can no longer be abused for DDOS attacks.

---

GeeksCoreLibrary/GeeksCoreLibrary.csproj
GeeksCoreLibrary/Modules/Ftps/Enums/EncryptionModes.cs
GeeksCoreLibrary/Modules/Ftps/Enums/FtpTypes.cs
GeeksCoreLibrary/Modules/Ftps/Extensions/EncryptionModesExtensions.cs
GeeksCoreLibrary/Modules/Ftps/Factories/FtpHandlerFactory.cs
GeeksCoreLibrary/Modules/Ftps/Handlers/FtpsHandler.cs
GeeksCoreLibrary/Modules/Ftps/Handlers/SftpHandler.cs
GeeksCoreLibrary/Modules/Ftps/Interfaces/IFtpHandler.cs
GeeksCoreLibrary/Modules/Ftps/Interfaces/IFtpHandlerFactory.cs
GeeksCoreLibrary/Modules/Ftps/Models/FtpSettings.cs

Add handlers for FTPS and SFTP connections to handle default actions.
No ticket.

Add support for FTPS and SFTP connections.

---

GeeksCoreLibrary/Modules/Databases/Interfaces/IDatabaseHelpersService.cs
GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseHelpersService.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseHelpersService.cs

Add helper function to optimize tables by name.
https://app.asana.com/0/1201027711166952/1203581518477359

Add option to optimize tables.

---

GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs

The order process often used the default account entity type instead of the one of the logged in user.

Fixed account entity type user in order process

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

The columns for `wiser_dashboard` and `wiser_login_log` have been updated.
This is in preparation for a Wiser PR (that in turn is waiting for another GCL PR to be merged first).
Asana: https://app.asana.com/0/1201027711166952/1203237258080996

Updated the columns used in the Wiser dashboard

---

GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs

The logging was lacking in some areas, and completely absent in other parts. Also updated the logging method calls to remove some warnings that the compiler was giving.
Asana: https://app.asana.com/0/1200923549887805/1204151769983299

Improved ConfiguratorsService logging

---

GeeksCoreLibrary/Components/OrderProcess/Interfaces/IOrderProcessesService.cs
GeeksCoreLibrary/Components/OrderProcess/Services/CachedOrderProcessesService.cs
GeeksCoreLibrary/Components/OrderProcess/Services/DecoratorOrderProcessesService.cs
GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs

Documentatie: https://app.nuclino.com/Happy-Geeks/Development/Technical-documentation-5fb5c6ee-e9b9-4fe6-a51c-b8a4021cab13
Asana ticket: https://app.asana.com/0/1200346761113317/1203533496760783

OrderProcess - Added functionality to be able to execute custom code in the order process.

---

GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs

Add an indication what ConfiguratorApi item was used and what the request was so it can quickly be reproduced.
https://app.asana.com/0/1200923549887805/1204129973412343

Improve logging for price API calls in the configurator.

---

GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs
GeeksCoreLibrary/Modules/Branches/Enumerations/CreateBranchEntityModes.cs
GeeksCoreLibrary/Modules/Branches/Models/BranchEntitySettingsModel.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

Added information to support the copying of items to a branch based on results of a data selector.
https://app.asana.com/0/1201027711166952/1203918305457021

Add data selectors for branches during creation.

---

GeeksCoreLibrary/Components/OrderProcess/Models/PayNLSettingsModel.cs
GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Modules/Payments/Enums/PaymentServiceProviders.cs
GeeksCoreLibrary/Modules/Payments/Models/PayNL/Amount.cs
GeeksCoreLibrary/Modules/Payments/Models/PayNL/Integration.cs
GeeksCoreLibrary/Modules/Payments/Models/PayNL/TransactionStartBody.cs
GeeksCoreLibrary/Modules/Payments/Services/PayNLService.cs

Add new PayNlService for Pay nl transactions.

Add support for payment provider Pay.nl 

---

GeeksCoreLibrary/Components/Filter/Filter.cs

* All filter items can now use the "`{querystring}`" replacement. Previously only filter groups could use the replacement.
* Slider filter template can now use formatters for its replacements.
* Updated some code with suggestions from Rider to reduce the amount of warnings.
https://app.asana.com/0/1199894242406919/1204290530927550

Updated Filter component

---

GeeksCoreLibrary/GeeksCoreLibrary.csproj
GeeksCoreLibrary/Modules/Payments/Helpers/Mollie/IOrderRequestBuilder.cs
GeeksCoreLibrary/Modules/Payments/Helpers/Mollie/OrderRequestBuilder.cs
GeeksCoreLibrary/Modules/Payments/Services/MollieService.cs

https://app.asana.com/0/0/1204379656118738/f
Rewrite the Mollie payment service so it uses the Order api instead of the Payment api

Rewrite mollie payment to order

---

GeeksCoreLibrary/Components/OrderProcess/Models/BuckarooSettingsModel.cs
GeeksCoreLibrary/Components/OrderProcess/Models/Constants.cs
GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Modules/Payments/Enums/Buckaroo/HashMethods.cs
GeeksCoreLibrary/Modules/Payments/Enums/Buckaroo/PushContentTypes.cs
GeeksCoreLibrary/Modules/Payments/Models/StatusUpdateResult.cs
GeeksCoreLibrary/Modules/Payments/Services/BuckarooService.cs

The Buckaroo service status update now also supports form values, in case the Buckaroo settings are set to use "post" updates instead of "json".
Asana: https://app.asana.com/0/1201394730777422/1204561856955516

Extended Buckaroo status update

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Core/Interfaces/IWiserItemsService.cs
GeeksCoreLibrary/Core/Services/CachedWiserItemsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

as per asana issue: https://app.asana.com/0/0/1203991871791882/f
mostly took over Gilian's changes from 2b52c1fb8ca5beeefbed687e9b70169ae754ac31 on JCL repo and made tweaks where needed.
testing method:
Ran wiser3 locally and used wiserdemo to add,edit and delete some products as well as children elements.

remove On duplicate key from wiserItemService

---

GeeksCoreLibrary/Modules/Templates/Middlewares/RewriteUrlToTemplateMiddleware.cs

Improved RewriteUrlToTemplateMiddleware to check if the current URL already matches any controller route. If it does, then we will let that controller handle the page. 
This way we shouldn't have problems anymore that when someone adds a regex to a template that matches an API controller or a javascript controller (gcl_general.js) for example, that those functions then don't work anymore.
Asana ticket: https://app.asana.com/0/1201027711166952/1204447399012145

Improved RewriteUrlToTemplateMiddleware

---

GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Fixed an issue where the image template would skip over an image due to a bad index check.
https://app.asana.com/0/1201394730777422/1204602363328574

Fixed image templating

---

GeeksCoreLibrary/Modules/Templates/Middlewares/OutputCachingMiddleware.cs

https://app.asana.com/0/0/1204529774481193/f
Add default setting as fallback for template caching time in caching middleware

Caching output fallback

---

GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/OutputCachingMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Models/Constants.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Also made some changes so that we don't show detailed exceptions on production and added logging for those exceptions.
Asana ticket: https://app.asana.com/0/1200346761113317/1204759101934835

If a page contains an error, it will no longer be cached.

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Asana ticket: https://app.asana.com/0/1200346761113317/1204125836006082

Added support for formatters, such as :Raw, to translations and stystem objects.

---

GeeksCoreLibrary/Components/OrderProcess/Models/Constants.cs
GeeksCoreLibrary/Components/OrderProcess/Models/PaymentMethodSettingsModel.cs
GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs

https://app.asana.com/0/1201394730777422/1204562312086552/f
Add Min Max checks to payment methods

Add Min Max checks to payment methods

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs

https://app.asana.com/0/1201394730777422/1204619084110932/

Save user confirmation mail and subject with order

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs

solve bugs related to incorrect parsing of values related to minmax payment provider options

solve bugs related to incorrect parsing of values related to minmax

---

GeeksCoreLibrary/Components/Filter/Filter.cs
GeeksCoreLibrary/Components/Repeater/Repeater.cs

https://app.asana.com/0/1201394730777422/1203410113254092/f

Filter and repeater enhancements

---

GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs

https://app.asana.com/0/7257459017111/1204954357441340

Allow anonymously connecting to SMTP servers.

---

GeeksCoreLibrary/GeeksCoreLibrary.csproj
GeeksCoreLibrary/Modules/Exports/Interfaces/ICsvService.cs
GeeksCoreLibrary/Modules/Exports/Services/CsvService.cs

https://app.asana.com/0/1201027711166952/1204576912230132/f

Add CSV Service for data conversion

---

GeeksCoreLibrary/Core/Models/WiserTableNames.cs

needed for: https://github.com/happy-geeks/wiser/pull/299

add new table name constant for use with styled output

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

needed for: https://github.com/happy-geeks/wiser/pull/299

add wiser table definion for wiser styled output

---

GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs

Added new productcode that must be used for packages that are send to Belgium

Added new productcode for packages that are send to Belgium

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs

Fixed a regression in the rendering of sub-steps for the legacy mode. The sub-steps would in some situations receive the wrong step number. Also removed some pointless component mode checks.
[Asana ticket](https://app.asana.com/0/1200923549887805/1205066333416700)

Fixed issue in sub-step rendering for legacy mode

---

GeeksCoreLibrary/Core/Cms/CmsComponent.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs

Scripts that are added using their relative URL now get turned into absolute ones.
[Asana ticket](https://app.asana.com/0/1200346761113317/1204915214406759)

Turn relative script URLs into absolute ones

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs

- Progress bar replacement now gets done after summary replacement, so the summary template also supports the standardized progress bar.
- Fixed multiple values for dependency values not working.
- Fixed multiple values for conditional requirements not working.
[Asana ticket](https://app.asana.com/0/1200923549887805/1205143134029060)

Configurator - Various changes and fixes

---

GeeksCoreLibrary/Components/Account/Account.cs

Allow a specific URL to be set, such as the product page to redirect back to after the login.
https://app.asana.com/0/1181344841509250/1204447865234190

Allow a redirect URL to be set through the query string.

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/Configurator/Models/VueConfigurationPriceModel.cs
GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Added a price calculation method to be called from the client side to (re)calculate prices.
[Asana ticket](https://app.asana.com/0/1200923549887805/1205159318777212)

Vue Configurator - Added price calculation method

---

GeeksCoreLibrary/Components/Configurator/Models/VueStepDataModel.cs
GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs

Steps can now become optional if they don't have options.
[Asana ticket](https://app.asana.com/0/1200923549887805/1205145414480048)

Vue Configurator - Step requirement conditions

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/Configurator/Models/VueConfiguratorDataModel.cs
GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs

The summary functionality of the Vue Configurator has been removed in favor of just creating an additional step that represents the summary.
[Asana ticket](https://app.asana.com/0/1203532238643488/1205325398219218)

Vue Configurator - Removed summary

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/Core/Middlewares/IpAccessMiddleware.cs

https://app.asana.com/0/1199894242406919/1204807852136592
Add functionality to black- or whitelist IPs by domain name

Add middleware to block or whitelist ip addresses

---

GeeksCoreLibrary/Modules/Databases/Services/DocumentStoreConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDocumentStorageService.cs

https://app.asana.com/0/1200346761113317/1205346498689088/f
Add branching support for document store. Connect using the branch database name if it has been set.
Also includes some code cleaning

Add branching support for document store

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

https://app.asana.com/0/0/1204853567388910/f

Update lastUpdate in tabledefinitions

---

GeeksCoreLibrary/Modules/Ftps/Handlers/FtpsHandler.cs
GeeksCoreLibrary/Modules/Ftps/Handlers/SftpHandler.cs

Asana ticket: https://app.asana.com/0/1205090868730163/1205547174932326

FTP - Fixed problem that downloading and deleting files would also download and delete symbolic links and directories.

---

GeeksCoreLibrary/Modules/GclConverters/Services/HtmlToPdfConverterService.cs

https://app.asana.com/0/1144661858028300/1205678181636670

Made PDF generation not dependent on httpContext

---

GeeksCoreLibrary/Components/DataSelectorParser/Services/CachedDataSelectorParsersService.cs
GeeksCoreLibrary/Components/OrderProcess/Services/CachedOrderProcessesService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/WebPage/Services/CachedWebPagesService.cs
GeeksCoreLibrary/Core/Services/CachedRolesService.cs
GeeksCoreLibrary/Core/Services/CachedWiserItemsService.cs
GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseHelpersService.cs
GeeksCoreLibrary/Modules/Languages/Services/CachedLanguagesService.cs
GeeksCoreLibrary/Modules/Objects/Services/CachedObjectsService.cs
GeeksCoreLibrary/Modules/Redirect/Services/CachedRedirectService.cs
GeeksCoreLibrary/Modules/Seo/Services/CachedSeoService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs

Added the name of the current branche to the cache key.
Renamed all variables concerning this key to an identical naming: **cacheName** 
Ticket:
https://app.asana.com/0/1205090868730163/1205090748659356/f

Added branchName to caching keys (renamed all vars to identical naming 'cacheName')

---

GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

The new MySQL connector changes the way how transactions work. These changes accommodate for those.
These are the changes:
* The transaction field is now of the `MySqlTransaction` type instead of `IDbTransaction`.
* Creating a transaction now sets the transaction on the commands.
* Similarly, when a transaction gets committed or rolled back, the transaction of the commands is also removed.
* The async variants are now used for transaction commits, rollbacks, and disposes.
[Asana ticket](https://app.asana.com/0/5038781037429/1205884675321526)

Fixes and changes for the MySQL connector

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

**asana:** https://app.asana.com/0/29553867016121/1205590045783437/f

update definition of styledoutput table

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

https://app.asana.com/0/1200923549887805/1203802664624132

Always return early if store type is hybrid, not only when new item is created.

---

GeeksCoreLibrary/Components/DataSelectorParser/Models/DataSelectorParserCmsSettingsModel.cs

Change bool props to string. 
Ticket: https://app.asana.com/0/1205090868730163/1206129973083292/f

Change some properties of DataSelectorParser to type string

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/Core/Models/PermissionModel.cs
GeeksCoreLibrary/Core/Services/RolesService.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

These permissions are not used (yet) in the GCL, they are used in an API of another project.
Asana ticket: https://app.asana.com/0/1205727761850957/1206193274458372

Added functionality for setting endpoint permissions

---

GeeksCoreLibrary/Modules/Databases/Interfaces/IDocumentStoreConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/DocumentStoreConnection.cs

Added a method that allows the connection string to be changed in the document store.
[Asana ticket](https://app.asana.com/0/1200923549887805/1203802664624132)

Allow connection string change in document store

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketCmsSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/Databases/Helpers/QueryHelpers.cs
GeeksCoreLibrary/Modules/Databases/Interfaces/IDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs
GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IStringReplacementsService.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs
GeeksCoreLibrary/Modules/Redirect/Middlewares/RedirectMiddleWare.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Fixed several issues that we ran into while converting one of our customers to the GCL:
* Added option to baskets to be able to load them without loading basket lines. Sometimes we only need to get the name of the basket for example and don't need the lines.
* Added property `ForcedBasketId` to basket settings, so that we can load a specific basket instead of whichever basket is currently linked to the user. Some customers have sites where users can have multiple baskets and we need to be able to load specific baskets for that.
* Fixed problem that doing basket replacements on a template would not work for prices and some other things, because there was a conflict with 2 different functionalities using the same syntax.
* Added better support for separate write and read connection strings. …

General fixes for webshops

---

GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs

Asana tickets: https://app.asana.com/0/1200923549887805/1206580185833024

Made a change to try and fix the issue that some scripts would get duplicate host names

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Templates/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Modules/Templates/Models/Template.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Asana ticket: https://app.asana.com/0/1151477971646641/1202937516126742
Corresponding Wiser PR: https://github.com/happy-geeks/wiser/pull/512

Added option to cache templates per user separately

---

GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

Sometimes we get the error "This MySqlConnection is already in use.". So far I can't figure out the exact cause, but to properly fix it we probably need to refactor a big part of the GCL by making MySqlDatabaseConnection transient. So for now, I added this workaround that just retries the query when the error occurs.
Asana ticket: https://app.asana.com/0/1200346761113317/1206556885253137

Workaround for the error "This MySqlConnection is already in use."

---

GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs

https://app.asana.com/0/1144661858028300/1206139426172844
Pull request https://github.com/happy-geeks/geeks-core-library/pull/524 depends on this pull request.

Return message ID from SMTPeter API

---

GeeksCoreLibrary/Core/Models/WiserTableNames.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

pr related to / needed by :  https://github.com/happy-geeks/wiser/pull/527

update def and table names for "wiser_parent_updates"

---

GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs
GeeksCoreLibrary/Core/Middlewares/IpAccessMiddleware.cs

Added code to never block localhost

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Saving parent_item_id to aggregation table.
Caution: This is a breaking change, because the parent_item_id column must be present in an existing aggregate table. If a new aggregate table is generated, the column will be included.

Saving parent_item_id to aggregation table

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Added replacement for relative URL

Added replacement for relative URL

---

GeeksCoreLibrary/Core/Models/WiserItemModel.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Added ordering to WiserItemModel, because it was missing.

Added ordering to WiserItemModel

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Added support for replacing "{Guid}" (or "{Uuid}") with generated GUID.
Tested the replacement in a customer setting.
N/A
[Asana ticket](https://app.asana.com/0/1199894242406919/1206942538117160)

Added "{Guid}" replacement

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs

Handle empty URL's better
With an empty URL the GCL gives an error. Now it builds a URL if the URL is empty.

Handle empty URL's better

---

GeeksCoreLibrary/Components/Filter/Filter.cs
GeeksCoreLibrary/Components/Filter/Services/FiltersService.cs

Please include a summary of the changes and relevant motivation and context.
Tested it at projects that use the component to see if the same results as before the change were given.
N/A
N/A

Fix multiple places for possible SQL injection.

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs

Fixed empty string not handled correctly. I did this change because you don't want an error when the string is empty. Only null values where catched.
- [] I have made corresponding changes to the documentation
- [] I added new unit tests for my changes if applicable

Fixed empty string not handled correctly

---

GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs

Check GCL mdidlewares with and without trailing slash. Depending on the settings this is automatically added or removed from the URL before processing.
Tested for the WTS healtcheck endpoint and `templace.gcl` endpoint to see fi the correct results are still given for when the URL is a GCL middleware page and normal webflow when the URL is not a GCL middleware page.
N/A
https://app.asana.com/0/1200346761113317/1206039386998862

Improve check for GCL middleware

---

GeeksCoreLibrary/Modules/Templates/Middlewares/OutputCachingMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs

Fix problem with caching a file when no caching set was set.
Tested locally with different settings to trigger the different caching.
N/A
N/A

Fix content caching

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs

Move shoppingbasket functionality for HTML rendering from component to ShoppingBasketsService to make this functionality accessible from the backend
The GCL was attached to a project with basket printing functionality. I was able to succesfully print a PDF containing data from the basket.
Add any open pull requests from other projects that are related to this pull request that should be merged along with this one. If there are none, you can simply say "none" or "N/A", or just leave this section empty.
https://app.asana.com/0/1151477971646641/1206533651519633

Move HTML render function from ShoppingBasket component to service

---

.github/workflows/build-and-test.yml
GeeksCoreLibrary.Tests/Core/Services/WiserItemsServiceTests.cs
GeeksCoreLibrary.Tests/GeeksCoreLibrary.Tests.csproj
GeeksCoreLibrary.Tests/Modules/GclReplacements/Services/ReplacementsMediatorTests.cs
GeeksCoreLibrary.Tests/Modules/GclReplacements/Services/StringReplacementsServiceTests.cs
GeeksCoreLibrary.sln
GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

I have started working on creating unit tests for the GCL. This is not very far yet and still a lot of work. We decided that I'd make pull requests after every class that has been finished. I have finished unit tests for the `ReplacementsMediator` class now and started working on the `StringReplacementsService` and `WiserItemsService` classes. The unit tests that are in this branch, are all working, so they can be safely merged to `develop`, if approved.
While making these unit tests, I have also found some bugs in our code, so the unit tests are already doing their job. I have fixed these issues I found in this branch. That's why you also see some changed outside of the unit tests project.
I tested this by running all the unit tests in Rider and then fixing …

First few unit tests

---

GeeksCoreLibrary/Components/OrderProcess/Controllers/OrderProcessesController.cs
GeeksCoreLibrary/Components/OrderProcess/Interfaces/IOrderProcessesService.cs
GeeksCoreLibrary/Components/OrderProcess/Models/Constants.cs
GeeksCoreLibrary/Components/OrderProcess/Services/DecoratorOrderProcessesService.cs
GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs

Someone added code that could be used to circumvent the order process. That PR was approved, but after some discussion we decided to undo the changes, because we don't want people to be able to circumvent the order process. This causes the code to be harder to maintain and causes some security risks. You should always use the order process. We can always look into ways to make the order process easier/quicker to setup if that is the problem.
I tested this by using these changes on a webshop that uses the order process and checked if all steps of the order process are still working correctly.
https://github.com/happy-geeks/geeks-core-library/pull/527
https://app.asana.com/0/1200346761113317/1207204515940781

Removed code that allowed people to create an order without using the order process

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

Add the options column to the table definition for styled output
The column will be added to existing customers ensuring the query does not fail reading a missing column.
Ran the GCL in a local instance of Wiser to check if the column was added to the table.
N/A
https://app.asana.com/0/1201027711166952/1207258858022215/f

Add the options column to the table definition for styled output

---

GeeksCoreLibrary.Tests/Modules/GclReplacements/Services/ReplacementsMediatorTests.cs
GeeksCoreLibrary/Modules/GclReplacements/Extensions/StringReplacementsExtensions.cs

Add replacement formatter with Replace function. Meaning `{string:Replace(i,a)}` with value `will` will turn into `wall`
Added new formatter to existing replacement value, was not recognized then connected GCL with this feature and now the replacement worked as expected. Also added tests for the new formatter to ReplacementMediatorTests which ran succesfully.
N/A
https://app.asana.com/0/1151477971646641/1206533651519632/f

Add Replace formatter method

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

added 2 new columns for styled out put table
not
none
https://app.asana.com/0/1204371236183532/1206473300071322/f

add columns to styled out put table for time logging

---

GeeksCoreLibrary/Modules/Branches/Models/BranchActionBaseModel.cs
GeeksCoreLibrary/Modules/Branches/Models/CreateBranchSettingsModel.cs
GeeksCoreLibrary/Modules/Databases/Helpers/MySqlHelpers.cs
GeeksCoreLibrary/Modules/Databases/Interfaces/IDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

The branches functionality for the WTS was only made to work when both production and the branch database are located on the same server. For a certain customer we need to be able to have those databases on different servers. This needed several adjustments to our code. The biggest adjustment was that we can no longer directly copy data from database X to database Y if they are not on the same server. So I added functionality for bulk imports and some other little things.
I have tested this by creating and merging several branches on a test database of a customer. 
Pull requests for Wiser and the WTS will be added once this one has been accepted, so that I can create a new version of the GCL en add that to the WTS and Wiser. …

Database connection additions

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Please include a summary of the changes and relevant motivation and context.
the build was made, also set the parameter by hand to false in navicat to confirm it would skip the operation in the trigger, which it does
- [ x I have reviewed and tested my changes
- [ x I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x ] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [ x] I added new unit tests for my changes if applicable
none …

disable the performparentupdate during wiseritem operations

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Account/Interfaces/IAccountsService.cs
GeeksCoreLibrary/Components/Account/Models/UserCookieDataModel.cs
GeeksCoreLibrary/Components/Account/Services/AccountsService.cs

Adds supports for setting a CustomRole seperate from the Wiser roles. 
The value given in the role column in the login query will be usable as a CustomRole.
Tested to see if the CustomRole got set correctly after loggin in using username and password and  seperately after going through password reset with LoginAfterEvent active.
Tested omiting the role from the login query to see if it broke anything.
N/A
https://app.asana.com/0/1151477971646641/1207558096817514/

Add support for custom roles

---

GeeksCoreLibrary.Tests/Core/Extensions/StringExtensionsTests.cs
GeeksCoreLibrary/Core/Extensions/StringExtensions.cs

Added unit tests for the class `StringExtensions`. Also removed a function from that class that is not used anywhere.
I tested this by running all the unit tests in Rider.
N/A
https://app.asana.com/0/1200346761113317/1205099203785827

Unit tests for StringExtensions

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

i ran into this when trying to access the happy idiots wiser3 domain
with some debugging i found this mistake that needs to be fixed
locally
not related directly to a ticket

fix mistake in index creation wiserWiserItemLinkDetail

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Made a few changes to improve the performance of loading templates from the Wiser templatemodule. This was really slow in some cases.
N/A
https://app.asana.com/0/1199894242406919/1207820796886294

Template performance improvements

---

GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs

If the file name is provided in the response headers, use that instead of the default.
Tested by debugging if the file name is set correctly before and after the header.
N/A
https://app.asana.com/0/1199995500457439/1205499002931887

Get file name from header if provided

---

GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

Added support for TIFF images. 
I tested this by uploading an TIFF image in Wiser and then loading it in the GCL. I also checked if things like cropping work.
https://github.com/happy-geeks/wiser/pull/646
CON-261

Added support for TIFF images.

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Added support for using "x:raw" in SO variables
I can't remember. ☹️ I remember needing this for something, and I discussed it with Gilian, build this and it worked. But that was months ago and I have no idea what I needed it for.
none
n/a

Fixed support for raw variables in templates

---

GeeksCoreLibrary/Core/Models/GclSettings.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Controllers/NeDistriController.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Interfaces/INeDistriService.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/AdressModel.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/AuthenticationModel.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/AuthenticationResponse.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/BarcodeModel.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/BarcodeResponse.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/CreateOrderModel.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/CreateOrderResponse.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/OrderType.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/RuleModel.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Models/ShippingLabelRequestModel.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Services/NeDistriService.cs

Add endpoint to create a label for an order for the distributor NE Distriservice
In a project in which we had already implemented POSTNL label generation I created an action in Wiser for generating a label NE distriservice. I ran this locally without problems.
N/A
https://app.asana.com/0/1201394730777422/1206829070786599/f

Add endpoint for generating labels for NE DistriService

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs

Adds a check on environment when getting payment methods to make to possible to have a payment method be visible in test and acceptance but not yet on live. This is done by adding a bitwise check in the query for oayment methods.
Changed the published environment in an existing project to show and hide the method.
N/A
https://app.asana.com/0/1201394730777422/1206046313587802/f

Environment condition for payment method

---

GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Replaced all usages of webclient within the geeks-core-library solution with the usage of httpclient.
Tested the functionality of the methods in which the webclient's got replaced. For example, the GetWiserCdnFilesAsync, that I then tested on its functionality of the usage of the httpclient. Which still worked.
N/A
https://app.asana.com/0/1200346761113317/1204568383292724/f

Replaced all usages of webclient with httpclient

---

GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Reverts happy-geeks/geeks-core-library#651

Revert "Replaced all usages of webclient with httpclient"

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Removed code that deleted record from wiser_itemlink and related tables. This is too dangerouns to do, because wiser_itemlink can contain IDs from multiple tables (wiser_item, basket_wiser_item, product_wiser_item etc), so we can delete the wrong records then.
I tested this via Wiser, by deleting some items that also had records wiser_itemlink and checking in the database if those links are no longer being deleted.
N/A
https://app.asana.com/0/1201027711166952/1208234846710458

Removed code that deleted record from wiser_itemlink and related tables

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Because the cache wasn't skipped when getting wiser item details there would in certain circumstances be false negatives causing duplicate key errors when saving an item.
Tested while pair programming an issue caused by this bug. 
N/A
https://app.asana.com/0/1201394730777422/1208345414842553/f

Fix problem with caching when updating wiser items

---

GeeksCoreLibrary/Core/Interfaces/IHttpClientService.cs
GeeksCoreLibrary/Core/Services/HttpClientService.cs
GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Refactored pieces of code to use the `HttpClient` class instead of `WebClient`. A Singleton is used to create a single `HttpClient` instance, as per the recommendations of Microsoft.
Tested the various places where a `WebClient` was used to determine it still works with the new `HttpClient` implementation.
N/A
[Asana ticket](https://app.asana.com/0/1200346761113317/1204568383292724)

Use `HttpClient` instead of `WebClient`

---

GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs

Added option to always load the external scripts of a template over https.
Scripts where served over http on a page running on http. After this change and adjusting the setting, scripts were served over https.
N/A 
N/A

Made option to always load the scripts over https.

---

GeeksCoreLibrary/Core/Helpers/JsonHelpers.cs
GeeksCoreLibrary/Modules/DataSelector/Services/DataSelectorsService.cs

Exporting data selectors that have multiple different connections, had a few problems. First was that an invalid query was generated, which caused an exception. The second problem was that the output data had missing columns and values in the wrong columns.
I tested this in Wiser, by using the export module for exporting a data selector. This data selector retrieves products, their parent categories and their sub products.
N/A
https://app.asana.com/0/1151477971646641/1208407672827499

Fixed issues with exporting data selectors

---

GeeksCoreLibrary/Components/OrderProcess/Middlewares/RewriteUrlToOrderProcessMiddleware.cs
GeeksCoreLibrary/Components/WebPage/Middlewares/RewriteUrlToWebPageMiddleware.cs
GeeksCoreLibrary/Core/Middlewares/AddAntiForgeryMiddleware.cs
GeeksCoreLibrary/Core/Middlewares/AddCacheHeaderValueMiddleware.cs
GeeksCoreLibrary/Core/Middlewares/ClearCacheMiddleware.cs
GeeksCoreLibrary/Core/Middlewares/IpAccessMiddleware.cs
GeeksCoreLibrary/Core/Middlewares/RequestLoggingMiddleware.cs
GeeksCoreLibrary/Modules/ItemFiles/Middlewares/WiserItemFilesMiddleware.cs
GeeksCoreLibrary/Modules/Redirect/Middlewares/RedirectMiddleWare.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/RewriteUrlToTemplateMiddleware.cs

After someone fixed an issue which caused all kinds of database connection errors (https://github.com/happy-geeks/geeks-core-library/pull/682), I wanted to double check all other middlewares to make sure they don't also have the same problem.
Luckily they didn't, but I did clean up their code a bit.
I only tested if the project can be compiled. I have done no functional changes, so nothing can break from this.
https://github.com/happy-geeks/geeks-core-library/pull/682
No Asana ticket.

Checked and cleaned up middlewares.

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs

Added extra health check to just check the database connection.
I tested this by calling the different `/health` endpoints on a test website/database and see if they return the expected things.
N/A
No Asana ticket, this change is made based on some internal discussion.

Added extra health check to just check the database connection

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

When duplicating an item with all underlying items an error was given for a missing column that was being read. This has now been added in the `SELECT` statement.
Tested by duplciating an item with underlying items.
N/A
N/A

Fix duplication of items when duplicating with recursion

---

GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs
GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Components/Repeater/Repeater.cs
GeeksCoreLibrary/Components/WebForm/WebForm.cs
GeeksCoreLibrary/Core/Services/EntityTypesService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
GeeksCoreLibrary/Modules/DataSelector/Services/DataSelectorsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/RewriteUrlToTemplateMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs

Improved all ArgumentOutOfRangeExceptions that we throw, we used them in the wrong way in a lot of places, which caused unclear error messages.
I have tested one of these exceptions to make sure I was making the correct change. Did not test the rest, but that's not needed. The change is the same everywhere.
N/A
No Asana ticket. Just a general improvement.

Improved all ArgumentOutOfRangeExceptions

---

GeeksCoreLibrary/Components/OrderProcess/Models/OrderProcessSettingsModel.cs
GeeksCoreLibrary/GeeksCoreLibrary.csproj
GeeksCoreLibrary/Modules/DataSelector/Controllers/DataSelectorController.cs
GeeksCoreLibrary/Modules/GclConverters/Models/HtmlToPdfRequestModel.cs
GeeksCoreLibrary/Modules/GclConverters/Services/HtmlToPdfConverterService.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Services/NeDistriService.cs

Evo PDF has a new version that works with Chromium, which also works on Linux. The original Evo PDF did not work on Linux. Since we want to start hosting our projects on Linux, we need this.
~~NOTE: Don't merge this yet. We still have to buy a new license for this version of Evo PDF.~~
License key is bought, this can be merged now, once it's approved.
This was tested with one of our websites. We tested that project in a Docker container on Linux and eventually got it to work. These changes were also tested on Windows with that same project and also in Wiser.
N/A
https://app.asana.com/0/1200346761113317/1207757339323491

New Evo PDF package

---

GeeksCoreLibrary/Modules/HealthChecks/Services/DatabaseHealthService.cs

needed to make a small change to ensure the values area available 
ran it locally
Add any open pull requests from other projects that are related to this pull request that should be merged along with this one. If there are none, you can simply say "none" or "N/A", or just leave this section empty.
Add a link to the Asana ticket. Note that **_ONLY_** the URL should be added, not the name of the ticket!

tweak to settings loading for database healthcheck

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Modules/Templates/Models/Template.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

adding 2 checkboxes to the tempalte module to more easily set robots noindex,nofollow tags, these can still be overwritten if someone sets a preload query that fills these values as well 
tested by trying it on wiser demo, changed settings back and forth and made sure teh query approach still takes presidency
https://github.com/happy-geeks/wiser/pull/782
Add a link to the Asana ticket. Note that **_ONLY_** the URL should be added, not the name of the ticket!

add robots no index and no follow tags to templates

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Base/Services/ComponentsService.cs
GeeksCoreLibrary/Components/OrderProcess/Models/PaymentServiceProviderSettingsModel.cs
GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs
GeeksCoreLibrary/Components/Pagination/Models/PaginationLegacySettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs
GeeksCoreLibrary/Components/WebForm/WebForm.cs
GeeksCoreLibrary/Core/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Core/Interfaces/ICacheService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/Amazon/Services/CachedAmazonSecretsManagerService.cs
GeeksCoreLibrary/Modules/Communication/Models/AttachmentUrlsModel.cs
GeeksCoreLibrary/Modules/Communication/Models/WhatsAppSendMessageRequestModel.cs
GeeksCoreLibrary/Modules/Communication/Models/WhatsappBodyContentModel.cs
GeeksCoreLibrary/Modules/DataSelector/Interfaces/IDataSelectorsService.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Models/WiserItemFileExtraDataModel.cs
GeeksCoreLibrary/Modules/Languages/Services/LanguagesService.cs
GeeksCoreLibrary/Modules/Objects/Services/CachedObjectsService.cs
GeeksCoreLibrary/Modules/PostalServices/NeDistri/Services/NeDistriService.cs
GeeksCoreLibrary/Modules/PostalServices/PostNL/Interfaces/IPostNLService.cs
GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs
GeeksCoreLibrary/Modules/Redirect/Models/RedirectModel.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Models/PageCssModel.cs
GeeksCoreLibrary/Modules/Templates/Models/PageJavascriptModel.cs

Use Task.Delay instead of Thread.Sleep, to not block threads while waiting for something.
Also removed all unused usings from the entire project.
I just tested if the project still compiles and runs. Not much else to test.
N/A
No Asana ticket.

Use Task.Delay instead of Thread.Sleep, to not block threads while waiting for something.

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Improved the replacement function which can replace an instance of a class (serialized to JSON) in a string. The function couldn't handle the direct result of serializing an instance of a class. The function accepts the JValue type, but doesn't handle this type correctly. 
Called the function with a JValue as parameter without this code and with this code. Also tested with other types, like JObject. That still works.
N/A
Needed for: https://app.asana.com/0/1205727761850957/1205737148335936

Improve replacement function

---

GeeksCoreLibrary/Modules/OAuth/Controllers/OAuthController.cs
GeeksCoreLibrary/Modules/OAuth/Interfaces/IOAuthService.cs
GeeksCoreLibrary/Modules/OAuth/Models/Constants.cs
GeeksCoreLibrary/Modules/OAuth/Services/OAuthService.cs
GeeksCoreLibrary/Modules/OAuth/Views/OAuth/AuthorizationFailed.cshtml
GeeksCoreLibrary/Modules/OAuth/Views/OAuth/AuthorizationSuccessful.cshtml

Added a page/function to handle callbacks from OAUTH2 authorization tokens for the WTS. Some APIs we need to connect with, require this kind of authentication. This authentication requires a manual user login the first time. The WTS sends an email to the user with a link to login. That link will send them to the external system to login and then that system will send them back to this new page so that we can store the authorization code that gets sent with that. Then the WTS can use that code for further authentication.
By going through the authentication flow multiple times until everything works as intended.
Note: These PRs are can be reviewed/merged separately, they are not dependent on each other for compiling. …

Callback for OAUTH2 authorization tokens

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Removed unwanted code, see PR https://github.com/happy-geeks/geeks-core-library/pull/741/files.

Remove unwanted code

---

GeeksCoreLibrary/Core/Services/ScopedBackgroundService.cs

Added support for running more than one background service and did some code cleanup. I need this in another project, one that has 3 background services at the moment. But only the last registered service is actually being executed.
In the project I described above, I tested that all 3 background services run correctly.
N/A
N/A

Background service improvements

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketProductsCountSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs

New shopping basket mode called ProductsCount. It's responsible for creating new replacements with the information about the shopping basket lines and products quantities.
The changes were tested on a specific project, the GCL was loaded locally to the project and to Wiser, a new Template was built in Wiser and added to a page to test the new mode. Besides that some tests were performed using hard-coded product id's to emulate a product going to the shopping basket since this specific project don't have that functionality built yet.
N/A
https://app.asana.com/0/1205090868730163/1208341445967404/f

New shopping basket mode

---

GeeksCoreLibrary/Modules/GclReplacements/Extensions/StringReplacementsExtensions.cs

In several of the methods in StringReplacementExtensions a StringBuilder would be used just to append a couple of strings.
I've also changed the substring calls to range indexers.
Ran the unit tests and opened a GCL site and clicked around. I've ran the methods using the debug console in Rider with some test inputs.
N/A
N/A

Make some optimizations in the string replacement methods

---

GeeksCoreLibrary/Core/Views/Shared/_Layout.cshtml
GeeksCoreLibrary/Modules/Seo/Models/PageMetaDataModel.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs

Add dynamic html `lang` attribute in the Shared/_Layout.cshtml based on languageService's currentLanguageCode.
Loaded several webpages and checked if the html='xxx' changed based on the languageService's currentLanguageCode value.
none
https://app.asana.com/0/1205090868730163/1205508227308510

Add dynamic html lang based on languageService's currentLanguageCode

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

Add table definitions for wiser_user_roles.
Ran a web project that created the newly added table (fields).
none

Add missing wiser_user_roles table definition

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/GeeksCoreLibrary.csproj
GeeksCoreLibrary/Modules/OAuth/Controllers/OAuthController.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/IPagesService.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedPagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

We recently found out that the caching of templates and pages in the GCL did not work correctly. It would often not cache things correctly, it would often cache things that shouldn't be cached and clearing the cache also often didn't work correctly. This caused caching to not be useful or even usable in a lot of projects. We refactored all the code for caching to improve this, so that we can make better use of caching.
N/A
https://app.asana.com/0/1200346761113317/1206196759534099

Improved caching

---

GeeksCoreLibrary/Core/Helpers/FileSystemHelpers.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

This adds support for the image formats AVIF and JPEG XL.
Used a test project to see if the code can correctly work with AVIF and JPEG XL files.
N/A
N/A

Added support for AVIF and JPEG XL

---

GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs

Added code to make sure that Account replacements can never be done with data from unsafe sources (such as the URL or POST data).
By testing some templates that contain variables such as `{Account_UserId}` and checking if I can influence those values via the query string in the URL.
N/A
https://app.asana.com/0/1200346761113317/1209348862740316

Don't do account replacements via unsafe sources

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Saving the value of a combobox or multiselect with a link type that has "UseItemParentId" enabled would not actually update the "parent_item_id" field and would always just create a record in wiser_itemlink. This is now fixed.
Used a debug build in Wiser and tested the changes in a sandbox environment, trying different combinations of settings and confirming everything works as expected.
None.
[Asana ticket](https://app.asana.com/0/1205090868730163/1206056368421224)

Fixed some parent ID issues

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

Refactor price calculation logic for readability. This is done by turning into the if else statements into a single switch case using pattern matching. 
Openen a webpage in which many different calculations of a basket like with or without vat, vat only, etc are shown and compared the values with those before the change.
N/A
N/A

Refactor price calculation logic for readability

---

GeeksCoreLibrary/Core/Helpers/JsonHelpers.cs

Please include a summary of the changes and relevant motivation and context.
Called function with JSON with empty sub arrays. The result of the function was a empty array, while my input did have filled properties. After fixing the bug, the result of the function did contain my filled properties.
N/A
https://app.asana.com/0/1205727761850957/1209482881042612

Bugfix FlattenJsonArray when JSON contains empty sub arrays.

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs
GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/GeeksCoreLibrary.csproj
GeeksCoreLibrary/Modules/DataSelector/Controllers/DataSelectorController.cs
GeeksCoreLibrary/Modules/DataSelector/Services/DataSelectorsService.cs
GeeksCoreLibrary/Modules/GclConverters/Enums/PageOrientation.cs
GeeksCoreLibrary/Modules/GclConverters/Interfaces/IHtmlToPdfConverterService.cs
GeeksCoreLibrary/Modules/GclConverters/Models/HtmlTemplateConstants.cs
GeeksCoreLibrary/Modules/GclConverters/Models/HtmlToPdfRequestModel.cs
GeeksCoreLibrary/Modules/GclConverters/Services/HtmlToPdfConverterService.cs

There were still some problems with loading the GCL without Evo PDF, even if the project doesn't use the HTML to PDF converter. To fix this, we have removed all Evo PDF code from the base GCL and create a new sub-package with the Evo PDF code.
By loading a project that uses the GCL. FIrst by testing without the new package, to make sure that we get no more errors. Then by adding the new package and checking if the HTML to PDF converter works as expected.
https://github.com/happy-geeks/geeks-core-library-evopdf/pull/1
https://app.asana.com/0/1200346761113317/1207757339323491

Moved all Evo PDF specific code to a separate class library

---

GeeksCoreLibrary/Modules/Amazon/Services/AmazonS3Service.cs

A method that was made during development was accidentally left in. The method goes unused, so it's safe to remove it, cleaning up the class.
By making sure the project could still be compiled. The removed method was private, so it's not like it could be used outside of the scope of the class.
None.
There's no ticket for this PR. I found the unused method while working on something else.

Removed unused method in AmazonS3Service

---

GeeksCoreLibrary/Core/Models/HealthChecksSettings.cs
GeeksCoreLibrary/GeeksCoreLibrary.csproj
GeeksCoreLibrary/Modules/HealthChecks/Services/DatabaseHealthService.cs

For my intern assignment i extended the database Health check and modifed it 
I have run this locally and tested it on Playground
https://localhost:5001/health/
- [X ] I have reviewed and tested my changes
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [ X] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
N/A
https://app.asana.com/0/1208835101966609/1204600179629379/f

New Health check added for Databases

---

GeeksCoreLibrary/Components/Base/Services/ComponentsService.cs
GeeksCoreLibrary/Components/OrderProcess/Helpers/PrecompiledRegexes.cs
GeeksCoreLibrary/Components/OrderProcess/Middlewares/RewriteUrlToOrderProcessMiddleware.cs
GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Helpers/PrecompiledRegexes.cs
GeeksCoreLibrary/Components/ShoppingBasket/PrecompiledRegexes.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/WebPage/Middlewares/RewriteUrlToWebPageMiddleware.cs
GeeksCoreLibrary/Core/Cms/CmsComponent.cs
GeeksCoreLibrary/Core/Helpers/CssHelpers.cs
GeeksCoreLibrary/Core/Helpers/DatabaseHelpers.cs
GeeksCoreLibrary/Core/Helpers/PrecompiledRegexes.cs
GeeksCoreLibrary/Core/Helpers/StringHelpers.cs
GeeksCoreLibrary/Core/Models/Constants.cs
GeeksCoreLibrary/Core/Models/CoreConstants.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/Communication/Helpers/PrecompiledRegexes.cs
GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
GeeksCoreLibrary/Modules/DataSelector/Helpers/PrecompiledRegexes.cs
GeeksCoreLibrary/Modules/DataSelector/Services/DataSelectorsService.cs
GeeksCoreLibrary/Modules/Exports/Services/ExcelService.cs
GeeksCoreLibrary/Modules/GclReplacements/Extensions/StringReplacementsExtensions.cs
GeeksCoreLibrary/Modules/GclReplacements/Helpers/PrecompiledRegexes.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs
GeeksCoreLibrary/Modules/Redirect/Middlewares/RedirectMiddleWare.cs
GeeksCoreLibrary/Modules/Templates/Helpers/PrecompiledRegexes.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Refactor regexes with RegexOption.Compiled to Source generated regexes, this is a performance improvement.
Also I noticed almost all regexes have 2 seconds as time limit so I put this value into a constant so we can easily change this default.
Opened a GCL site and stepped through it to see whether anything was off.
N/A
https://app.asana.com/0/1205090868730163/1209125209349683/f

Refactor regexes with RegexOption.Compiled to Source generated regexes

---

GeeksCoreLibrary/Modules/Payments/Services/PaymentServiceProviderServiceFactory.cs

The FindTypeInLoadedAssemblies method looks through all types in the assembly to find the correct one for the given name. 
This change caches the found types in a ConcurrentDictionary to make subsequent payment provider retrievals faster.
Reloaded the checkout page and went throught and went through the checkout flow, creating and paying for a new order.
N/A
N/A

Optimize payment service provider retrieval for improved performance.

---

GeeksCoreLibrary/Core/Models/WiserTableNames.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

adding the productsApi feature to wiser
On wiserdemo and a copy of IG database, with postman
NOT YET, ill do this after intial usage is hooked up at IG
https://github.com/happy-geeks/wiser/pull/909
JIRA

Add productsApi

---

GeeksCoreLibrary/Core/Services/LinkTypesService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

There were still some small issues with linking items to a parent. Mostly with the ordering, there were some typos and one query was missing a check for link type, so it would return too many rows.
By using this branch in Wiser and creating some items. Then I also created a test project to create new items with parent IDs in several different ways and tested that.
N/A
I found this while working on an unrelated ticket. There is no specific asana ticket for this. This is the ticket that I was working on:
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1209921173095221

Fixed issues with ordering when creating items with parent id

---

GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs

In https://github.com/happy-geeks/geeks-core-library/pull/860 I accidentally pushed a change that shouldn't have which stops retrieval of page meta data in a component from working correctly. This reverts that.
This reverts a change to how it was before, I did not test this separately.
Reverts one of the changes of https://github.com/happy-geeks/geeks-core-library/pull/860
N/A

Fix caching logic for SEO data in CachedTemplatesService

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

Added wiser_entityproperty table changes for wiser custom property feature
on wiser_demo database
https://github.com/happy-geeks/wiser/pull/956
https://app.asana.com/1/5038780173035/project/1205385697833645/task/1207120716903559

Updated table for Wiser custom property groups

---

GeeksCoreLibrary.Tests/Core/Extensions/StringExtensionsTests.cs
GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs
GeeksCoreLibrary/Core/Extensions/StringExtensions.cs
GeeksCoreLibrary/Core/Helpers/RegexHelpers.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IStringReplacementsService.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs

Made the following changes:
* There was a problem that users could enter GCL variables in a checkout and the OrderProcess component would evaluate them, which could cause some sensitive data to leak. This has been fixed.
* Fixed problem that the `RemoveTemplateVariables` would not properly remove variables such as `[T{x}]` and [SO{x}]`.
* Added a new class `RegexHelpers` with a custom `Escape` method. The default `Regex.Escape` method of .NET does not escape the characters `}` and `]`, even though it should. This caused some regexes to not work as expected. This is fixed now.
* Fixed problem in `StripIllegalFilenameCharacters` that we never noticed before, because the `Regex.Escape` method we used was incorrect. Now that I fixed the regex escape, the unit tests for …

Fixed problems with replacements

---

GeeksCoreLibrary/Modules/Exports/Interfaces/IExcelService.cs
GeeksCoreLibrary/Modules/Exports/Services/ExcelService.cs

I needed streaming support for excel files so i refactored the existing logic, broke it up so we have no code duplication
hooked it up locally for a costumer project and used it
none
https://app.asana.com/1/5038780173035/project/1204371236183532/task/1210122797857071?focus=true

refactor ExcelService to support both paths and streams

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Fixed problem that certain types caused an `System.InvalidCastException: Object must implement IConvertible.` errors, in the `StringReplacementsService.FillStringByClass` method. This happened, for example, with `DateTimeOffset`, which cannot be cast to a string, it needs to be converted with a format.
Tested this in an API where I ran into this problem.
https://github.com/happy-geeks/FetimWebApi/pull/95
https://app.asana.com/1/5038780173035/project/1205727761850957/task/1209532878576612

Bugfix in JSON replacements
