GeeksCoreLibrary/Components/Pagination/Pagination.cs

The 'FullTemplate' now supports three new variables:
- pagenr: the current page number.
- lastpagenr: the last page number.
- totalitems: the total items in a result.

Additional replaces for pagination

---

GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketCmsSettingsModel.cs

The query properties for the Shopping Basket now have their
TextEditorType setting set to QueryEditor so Wiser will use the correct
editor.

Query editor for Shopping Basket query properties

---

GeeksCoreLibrary/GeeksCoreLibrary.csproj

SkiaSharp has been replaced by Magick.NET a while back, so SkiaSharp is
longer needed.

Removed SkiaSharp reference

---

GeeksCoreLibrary/Components/Repeater/Models/RepeaterCmsSettingsModel.cs
GeeksCoreLibrary/Components/Repeater/Repeater.cs

New functionality added for the repeater component for loading items up to a specific page number. This settings can be overruled using a querystring variable.
Also added functionality for replacing variabels of the firstrow in the between template of the repeater component.

Added functionality for loading items up to a specified page number

---

GeeksCoreLibrary/Modules/GclReplacements/Extensions/StringReplacementsExtensions.cs

Adds the formatter "Lowercase" and "Uppercase" to convert a string to lowercase or uppercase respectively. Both functions have an optional parameter to use invariant culture casing rules instead of the current culture's casing rules.

Added casing formatters

---

GeeksCoreLibrary/Components/Filter/Models/FilterAggregationSettingsModel.cs

The default HTML for the complete template of the Filter component uses {filters:Raw} and {summary:Raw}, but the ':Raw' part would cause the filters and summary not to render.

Fixed filter default complete template HTML

---

GeeksCoreLibrary/Components/Filter/Filter.cs
GeeksCoreLibrary/Components/Filter/Models/FilterGroup.cs

* Removed space in default filterParameter value.
* Changed slider values to decimals instead of doubles to avoid precision errors.
* Initial selected min and max values are now the min and max values.
* MinValue is now also converted to a string using the invariant culture.

Some filter changes and fixes

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Replacing variables inside variables (such as a request or database value inside a translation) now work correctly.

StringReplacementsService fix

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/ShoppingBasketUpdateItemSettingsModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/UpdateItemModel.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs

A new component mode called "UpdateItem" has been added to the ShoppingBasket component. This mode can update an existing item in the basket, capable of overwriting almost all properties. Only "connecteditemid", "type" and "quantity" cannot be updated.

Added "UpdateItem" mode to ShoppingBasket

---

GeeksCoreLibrary/Core/Extensions/StringExtensions.cs

Fixes the ConvertToSeo function replacing underscores with a dash.

Fixed underscore replace in ConvertToSeo

---

GeeksCoreLibrary/Modules/Templates/Controllers/JavascriptController.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs

JavaScript templates checked for the last-change date of CSS templates, and the Legacy templates service always served CSS and SCSS templates, except for CSS requests.

Fixed some issues with JS and (S)CSS templates

---

GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

This fixes an issue when the image templating couldn't find an image, that the no-image result would replace the entire template instead of just the image templating variable.

Fixed no-image issue in image templating

---

GeeksCoreLibrary/Modules/Languages/Models/Constants.cs
GeeksCoreLibrary/Modules/Languages/Services/CachedLanguagesService.cs
GeeksCoreLibrary/Modules/Languages/Services/LanguagesService.cs

The language code can now be set through a query string with the name 'GCLLanguageCode'. This value will not be cached, and is only valid for that single request.

Language code through query string support

---

GeeksCoreLibrary/Core/Extensions/StringExtensions.cs
GeeksCoreLibrary/Core/Models/GclSettings.cs

The EncryptWithAes and DecryptWithAes functions always used 8 bytes with a value of 0 as the salt, which is extremely weak. This new setting allows a custom salt to be set. Note that EncryptWithAesWithSalt and DecryptWithAesWithSalt do NOT use this new setting! Those functions always use a random salt.

Adds setting for the salt for AES encryption

---

GeeksCoreLibrary/Components/Filter/Services/FiltersService.cs

er werd gebruik gemaakt van ToMySqlSafeValue(true), in de query zelf zag ik dat de vergelijking met de filterwaarde als onderstaande gedaan werd
0.filtervalue >= '2' AND f0.filtervalue <= '120' dit gaat niet werken voor een varchar kolom, dus dan wordt het '120'+0 of de quotes weghalen was mijn beredenering. Dit gaat op andere plekken op dezelfde manier verkeerd. ik heb dit nu alleen voor happy deco werkend gemaakt.

slider uses numeric values, when enclosed with quotes the query yields no results

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
GeeksCoreLibrary/Components/Repeater/Repeater.cs
GeeksCoreLibrary/Core/Cms/CmsComponent.cs

Account component now always skips cache for all queries, as user data shouldn't be cached as it can change at any moment.

No query cache for Account queries

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs
GeeksCoreLibrary/Core/Cms/CmsComponent.cs
GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs

- After removing the last product from a basket, all non-product lines are also removed (coupons, shipping costs, etc.).
- Reloading the basket due to having an ExtraMainFieldsQuery or ExtraLineFieldsQuery now works.
- Invoking a method using callMethod will now add default values for optional parameters if they're absent.
- ShoppingBasket no longer supports callMethod. The forcedComponentMode functionality should be used instead.

Fixed some shopping basket issues

---

GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Modules/Templates/Models/Template.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

The "login required" option for templates is now supported. The templates service will return an empty template if a login is required, but no login is found (or if no HttpContext is available). The templates controller will redirect the user to whatever is set in the "login redirect URL" field, or return a 401 status (Unauthorized) if no redirect URL is set. Query and partial templates always return a 401 status if a login is required and no active login is found.

Login required support for templates

---

GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

The "login required" functionality didn't work due to issues with trying to open a DataReader while one is already opened. Also added a few "await" keywords to usings that call async functions.
Asana: https://app.asana.com/0/1201394730777422/1202458138134697

Fixed "login required" functionality for templates

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Any colons in the DateTime format string can now be escaped with a backslash (\\) to make them work. Also added the NowDateTime default replacement.

Fixed the DateTime formatter not working correctly

---

GeeksCoreLibrary/Components/OrderProcess/Services/CachedOrderProcessesService.cs

the answers of users are added to the fields in the steps object. If the object is cached all users got the reference to the same object so people could see the information of others. By always creating a new element users won't have the same reference.
https://app.asana.com/0/1201394730777422/1202673941324689

Remove caching of the steps object.

---

GeeksCoreLibrary/Components/Filter/Filter.cs

An empty filter would be created the first time a group is used. This checks if there is actually a previous group.
https://app.asana.com/0/1200896832146623/1202486506923788

Check if the previous filter group has a group.

---

GeeksCoreLibrary/Components/Repeater/Models/RepeaterCmsSettingsModel.cs
GeeksCoreLibrary/Components/Repeater/Repeater.cs
GeeksCoreLibrary/Modules/Seo/Models/PageMetaDataModel.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/IPagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs
GeeksCoreLibrary/Modules/Templates/Views/Shared/Template.cshtml

The Repeater component and the templates pre-load query can now set Open Graph meta tags.
https://app.asana.com/0/1201027711166952/1202945204173858

Add Open Graph support

---

GeeksCoreLibrary/Modules/Languages/Services/CachedLanguagesService.cs

This is because the language code was being cached the first time a request is made. Then all following requests would get the same language code from the cache, even if they were from a different domain with a different language.
https://app.asana.com/0/1167986948634679/1202698312678304

LanguagesService - Fixed bug that the language code was always the same, when caching is enabled.

---

GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IStringReplacementsService.cs
GeeksCoreLibrary/Modules/GclReplacements/Models/StringReplacementVariable.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

It is now possible to add default values by adding a "?" and then the default value to a variable within a Wiser HTML template.
For example {variable?1234}
[GCL: default waarde op kunnen geven voor variabelen {naam:defaultvalue}]
Asana ticket:
(https://app.asana.com/0/1201027711166952/1202879712279705)

Adding default values

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Account/Interfaces/IAccountsService.cs
GeeksCoreLibrary/Components/Account/Models/AccountCmsSettingsModel.cs
GeeksCoreLibrary/Components/Account/Models/Constants.cs
GeeksCoreLibrary/Components/Account/Models/UserCookieDataModel.cs
GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/Core/Models/CoreConstants.cs
GeeksCoreLibrary/Core/Services/CachedRolesService.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Modules/Templates/Models/Template.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

The Account component can now assign roles to users when creating or updating. The new query "Account roles Query" can be used for determining which roles a user will have when creating or updating. In addition, templates that require users to have a certain role will no longer load if the user doesn't have one of the required roles.
https://app.asana.com/0/1201027711166952/1202879712279688

User roles

---

GeeksCoreLibrary/Components/Account/Account.cs

It was accidentally left in during development of the user roles.

Removed an unused GetUserRolesAsync call

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

The `CalculateShippingCostsAsync` and `CalculatePaymentMethodCostsAsync` both called the `AddLineAsync` function which starts a transaction by default. However, in the flow of adding a product, a transaction would already be started at that point, causing an error. This is now fixed.
https://app.asana.com/0/1201394730777422/1202805894433129

Fixed shopping basket service transactions issues

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

When trying to create an item and immediately linking it to a parent ID, the `@newOrderNumber` user variable would get overwritten by the `newOrderNumber` paremeter value in some cases. The user paremeter has been renamed to `@newOrdering` to fix this issue.
https://app.asana.com/0/1200729155901577/1203271506272167

Fixed issue with determining ordering number

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

This is done because question mark is often used in teksts for translations and that caused problems with default values.
Asana: https://app.asana.com/0/1201027711166952/1203158028215086

StringReplacementsService - Default values now work with a pipeline (|) instead of question mark (?)

---

GeeksCoreLibrary/Modules/Templates/Models/TemplateDataModel.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

The external files of the linked JS and CSS templates are now also returned when calling the template endpoint of the templates controller.
Asana: https://app.asana.com/0/1200346761113317/1203224263717539

Return external files in template data endpoint

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Because question mark and pipeline caused conflicts with other things.
Asana task: https://app.asana.com/0/1201027711166952/1203158028215086

Changed default value separator to tilde (~)

---

GeeksCoreLibrary/Components/Pagination/Pagination.cs

Added functionality to return a 404 when the user requests a page nr which is higher than the allowed max.

Return 404 when pagination page nr higher than max

---

GeeksCoreLibrary/Modules/Redirect/Middlewares/RedirectMiddleWare.cs

Changed the `ToString` calls on the `fullUri` object to `AbsoluteUri` property to ensure it doesn't decode the URI and make incorrect assumptions about the query string being removed from the URL.

Fixed some errors in the redirect middleware

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

The workflow query (insert or update query) will now also replace default variables if they're enquoted, either in single quotes or double quotes.
Asana: https://app.asana.com/0/1200346761113317/1203329345327784

Replace enquoted variables in workflow query

---

GeeksCoreLibrary/Core/Helpers/FileSystemHelpers.cs
GeeksCoreLibrary/Core/Services/CacheService.cs
GeeksCoreLibrary/Modules/Barcodes/Services/CachedBarcodesService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs
GeeksCoreLibrary/Modules/Templates/Middlewares/OutputCachingMiddleware.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs

* The folders no longer get automatically created because often the user running the website does not have enough permissions.
* Reading and writing to the content or files cache folder will generate warnings in the logs when the folder is missing.
* If the content files folder is missing, all images and files will return a 404.
* The barcodes service will generate a warning in the logs when the content cache folder is missing.
Asana: https://app.asana.com/0/1200346761113317/1203064603974583

Cache folder changes

---

GeeksCoreLibrary/Components/Pagination/Pagination.cs

The Pagination component would always return a 404 response when the result was empty. This is because the current page number always starts at one, but the last page number will be zero if the SQL query returned an empty result set.
Asana: https://app.asana.com/0/1200923549887805/1203352369676148

Fixed Pagination component on empty results

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Modules/Templates/Models/Template.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Add functionality to mark an HTML template as a partial to ignore the header and footer template when requesting a template through an XHR call. Templates marked as partial no longer need to use "ombouw=false".
Combined with Wiser pull request: https://github.com/happy-geeks/wiser/pull/194
https://app.asana.com/0/1200346761113317/1203257614129593/

Ignore header and footer when template is requested that is a partial.

---

GeeksCoreLibrary/Components/Pagination/Models/PaginationCmsSettingsModel.cs
GeeksCoreLibrary/Components/Pagination/Models/PaginationLegacySettingsModel.cs
GeeksCoreLibrary/Components/Pagination/Pagination.cs
GeeksCoreLibrary/Modules/Seo/Models/PageMetaDataModel.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/IPagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs
GeeksCoreLibrary/Modules/Templates/Views/Shared/Template.cshtml

Adds a new option to the `Pagination` component called `AddPreviousAndNextLinkRelationTags` that will add `<link>` tags to the `<head>` section of the page for the next and previous page.
Asana: https://app.asana.com/0/1201926624799606/1202014165901940

Pagination "rel=prev" and "rel=next" support

---

GeeksCoreLibrary/Modules/Seo/Services/CachedSeoService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs

* Default port no longer gets added to hostname (e.g. site.com:443).
* The SEO information is now saved with the entire URL in the cache key to avoid issues with pages getting the wrong canonical URL.
Asana: https://app.asana.com/0/1201926624799606/1202014165901938

Default canonical URL fixes

---

GeeksCoreLibrary/Components/WebPage/Services/WebPagesService.cs

When a webpage is in two folders and those folders have a shared part the order was deciding in which webpage was selected.
For example a webpage named "information" in the folders "about products" and "about" would give the webpage in the "about products" folder instead of "about" when the path must contain "about".
By adding an empty string before and after the path it will create a "/" before and after so the path contains can be set with "/about/" to refer to the correct folder.
https://app.asana.com/0/1200346761113317/1203198059524791/

Improve the query for the path contains functionality in webpages.

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Core/Interfaces/IWiserItemsService.cs
GeeksCoreLibrary/Core/Services/CachedWiserItemsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

This is made for converting baskets to orders, so that the added_on value of the item will be the date and time that the order was created, instead of when the original basket was created.
Asana ticket: https://app.asana.com/0/1185430495431408/1203600261682709

Added option to reset the added on datetime when changing the entity type of an item.

---

GeeksCoreLibrary/Modules/Templates/Middlewares/RewriteUrlToTemplateMiddleware.cs

If a path starts with "/api/" don't try to get a corresponding template. This way custom endpoints can be called without the regex of a template finding a match on the path.
Ticket: https://app.asana.com/0/1200923549887805/1203320858738332

Ignore API paths when checking templates.

---

GeeksCoreLibrary/Modules/GclReplacements/Extensions/StringReplacementsExtensions.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Added new formatter called `QrCode` which will return a URL to generate a QR code for a string. Also fixed the `FillStringByClass` and `FillStringByClassList` functions not passing the `evaluateTemplate` parameter to recursive calls.
Asana: https://app.asana.com/0/272408684267078/1203234477426276

Update for the string replacements service

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/Configurator/Models/SubStepHtmlModel.cs

Changed the way the sub steps can be placed in the HTML by allowing only certain sub steps (by either ID or name) to be placed in specific parts of the HTML, by using pipes to separate the IDs or names of the substeps, like so: `{substeps|789|123}` or `{substeps|Step 4|Step 2}`. The regular `{substeps}` variable is also still available.
Asana: https://app.asana.com/0/1200346761113317/1202855528276892

Configurator sub steps placement

---

GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs

When a configuration is created about half the time is spend on the history, since each (selected/answered) option in the configurator is saved the time needed increases.
When creating the configuration all the previous values are nothing, therefore the history is useless at this stage.
https://app.asana.com/0/1200923549887805/1203802664624132

Don't save history when creating a configuration.

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Note: This only applies for tenants running on MySQL 5.7.
Fixed a query error in the `RemoveItemLinksById` of the `WiserItemsService` due to using an alias in a single-table `DELETE` statement which doesn't work on MySQL 5.7 databases.

Fixed query error in the itemlink remove method

---

GeeksCoreLibrary/Modules/Languages/Services/CachedLanguagesService.cs

In some cases the CurrentLanguageCode was null, which caused a problem with missing translations. This commit should fix that.
Asana ticket: https://app.asana.com/0/1200923549887805/1203513747164244

Fixed problem that sometimes translations were missing

---

GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Refactored the way the configurator saves the logging of save API calls.
Set "alwaysSavesValues" to true when creating a new item. Since all values are new there is no need to check if the value has been updated.

Improve performance for saving items.

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

The variable `{Environment}` can now be used to get the current environment the website is currently running on as an integer value:
* 1 = development
* 2 = test
* 4 = acceptance
* 8 = live
This can be used in SQL queries to check if an item is published for the current environment, like so:
```mysql
item.published_environment & {Environment} = {Environment}
```
Note: There is no ticket for this pull request.

Added environment as a default replacement

---

GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs
GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Core/Helpers/StringHelpers.cs
GeeksCoreLibrary/Core/Helpers/UriHelpers.cs

Concept orders were converted twice to an order. This causes the "AfterConvertToOrder" to be called twice.
On summary the basket information was available for replacements instead of the order. The order is now added to the URL for the PSP to know for which order to load the information.
https://app.asana.com/0/1201763244049195/1203965426621542
https://app.asana.com/0/1201763244049195/1203965426621547

Fix multiple bugs in the order processing.

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Fixed a potential `NullReferenceException` in the `DoSessionReplacements` method when the session feature is enabled, but the session itself being `null`.
There is no ticket for this PR.

Fixed potential NRE in DoSessionReplacements

---

GeeksCoreLibrary/Core/Extensions/DatatableExtensions.cs
GeeksCoreLibrary/Modules/DataSelector/Services/DataSelectorsService.cs
GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

The optional connections in data selectors would add a single empty item in the subitems array if an item didn't actually have a connection of that type. Now it doesn't add an array at all if no child items are found.
Asana: https://app.asana.com/0/1201027711166952/1203285888728845

Changed how optional connections are handled

---

GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseHelpersService.cs

Some fixes for the `MySqlDatabaseHelpersService`:
* The `AddAfterColumnName` functionality didn't work due to the name being added as a parameter to the MySQL command, which would turn it into a string even though it's not supposed to be a string.
* The `DropColumnAsync` method didn't work due to using a parameter for the column name, which would turn it into a string, but that makes the query invalid.
Asana: https://app.asana.com/0/5038781037429/1203237258080996
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203237258080996

Fix for adding and dropping MySQL table columns

---

GeeksCoreLibrary/Components/OrderProcess/Controllers/OrderProcessesController.cs

The `PaymentInAsync` and `PaymentReturnAsync` endpoints are usually called by external systems which would be blocked by the anti-XSRF protection. The `IgnoreAntiforgeryToken` attribute will allow these endpoints to be called without having to disable the protection for the entire website.

OrderProcess - Disable XSRF protection for payment updates

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs

Overwrite the webhook domain that the PSP calls after handling the payment. This can be used for example when the website makes use of a waiting room, blocking incomming traffic, to allow PSPs to always call the webhook.
https://app.asana.com/0/1201763244049195/1204080782040329

Add option to overtrite the webhook domain to be used by the PSP.

---

GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseHelpersService.cs

Various methods in the "CachedDatabaseConnection" and "CachedDatabaseHelpersService" that returned a Task didn't have the "async" modifier, and could potentially cause race conditions as the method could finish executing before the Tasks actually finished. These methods now all have the "async" modifier and use "await" for all function calls that are async.
Asana: https://app.asana.com/0/1200923549887805/1204012695375381

Added async modifier to methods returning a Task

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

The save function of the `ShoppingBasketsService` would generate an error when trying to remove linked items if `createNewTransaction` was set to false, but a transaction was already started prior to calling the save function. The function would try to start a second transaction (which is not possible).

Fixed error in shopping basket save function

---

GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs

The `Hostname` default replacement variable will now include the port of the request URL if one was added. Note that port 80 and port 443 will not be added unless they're explicitly added in the URL.
Asana: https://app.asana.com/0/1200923549887805/1204077971372781

Include port in "Hostname" variable

---

GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

JavaScript and stylesheet templates are now excluded when they have a URL regex set and the URL doesn't match that regex.
Asana: https://app.asana.com/0/1200923549887805/1204096541331925

Support for URL regex for CSS and JS templates

---

GeeksCoreLibrary/Core/Exceptions/GclQueryException.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

If an exception was thrown for example an invalid query it would only show a small part of the query. If the invalid syntax is at the end there is no information.
The full query is added to the exception to indicate where it goes wrong.
https://app.asana.com/0/1200346761113317/1203601476439864

Add the executed query to thrown exceptions.

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Account/Interfaces/IAccountsService.cs
GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Core/Models/GclSettings.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

* Changed functionality to no longer automatically retry single queries if that query is part of a transaction.
* Added setting for the time to wait before retrying a query or transaction in which a deadlock or similar error occurred.
* Fixed problem that logs did not actually show the query.
* Added automatic retries for deadlocks to all transactions.
Asana ticket: https://app.asana.com/0/1200346761113317/1203974810597720

Some improvements to handling of deadlocks

---

GeeksCoreLibrary/Modules/Communication/Interfaces/ICommunicationsService.cs
GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs

When creating a communication in the queue the ID of that communication was only returned in some cases. This change makes sure this value is always returned.
https://app.asana.com/0/7257459017111/1204050481956757

Return the created communication ID.

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs

Fixed a bug with the main step name in Vue mode where it would always use the name of the first main step.
Asana: https://app.asana.com/0/1200923549887805/1204562111037551

Configurator Vue mode - Fixed main step name issue

---

GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IReplacementMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

The previous solution was to create a new scope inside the AccountsService, but that caused another problem; The DoReplacements function adds parameters to the IDatabaseConnection, but that connection is also created a new due to having a new scope. So those parameters would not be available outside that scope, which caused errors.
Asana ticket: https://app.asana.com/0/1200346761113317/1204775665405292

Introduced an intermediary service for replacements to fix a problem with circular dependency between StringReplacementsService and AccountsService

---

GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Some methods that were moved to the `ReplacementsMediator` were still being called in the `StringReplacementsService`. The methods are now public methods that are defined in the `IReplacementsMediator` interface.
Asana: https://app.asana.com/0/1200346761113317/1204125836006082

Fixed missing methods in StringReplacementsService

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/Configurator/Models/VueStepDataModel.cs
GeeksCoreLibrary/Components/Configurator/Models/VueStepOptionDataModel.cs
GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs
GeeksCoreLibrary/GeeksCoreLibrary.csproj

- Fixed caching issue;
- Static extra data is loaded through initial query instead of one query per step (this improves performance);
- Extra data from the extra data query can now overwrite static extra data values;
- Support for steps that open modal when clicking on option instead of making a selection.
Asana ticket for the caching issue fix: https://app.asana.com/0/1200923549887805/1204833966511650

Configurator Vue mode update

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs

Some properties would never get saved if an order used "NOPSP" payment method. This fixes that by adding an additional save call. Also moved setting the email body and subject details on the order to a different place.
https://app.asana.com/0/1201394730777422/1204619084110932

Added save call for order in order process service

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs

The Vue mode of the configurator now supports the `{progress}` variable to place the progress HTML template.
https://app.asana.com/0/1200923549887805/1204470224534354

Adds support for the progress template

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs

The table was never checked for changes. Since the table always need to e updated the check is done on launch of a project using the GCL.
https://app.asana.com/0/1200346761113317/1204986264877999

Check changes to wiser_entity table on launch of the GCL project.

---

GeeksCoreLibrary/Modules/Templates/Extensions/DbDataReaderExtensions.cs

Some columns are not available for legacy templates, causing errors when trying to load a template. These columns are now checked for availability before reading them to avoid these errors.
[Asana ticket](https://app.asana.com/0/1199894242406919/1205056437179043)

Added checks for columns when loading template

---

GeeksCoreLibrary/Components/Configurator/Configurator.cs
GeeksCoreLibrary/Components/Configurator/Interfaces/IConfiguratorsService.cs
GeeksCoreLibrary/Components/Configurator/Services/CachedConfiguratorsService.cs
GeeksCoreLibrary/Components/Configurator/Services/ConfiguratorsService.cs

When the endpoint and body are the same during the loading of multiple steps the responses will be reused. This way less calls need to be made to an external API. Since the data hasn't changed during loading the response should be the same if the endpoint and body are the same.
https://app.asana.com/0/1200923549887805/1205082123491891

Reuse responses if the expected result is the same.

---

GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs

The `removeSvgUrlsFromIcons` option that would remove part of the href in SVG icons would return an error if the regex match would return an empty string. This change fixes that.

Fixed a potential String.Replace error

---

GeeksCoreLibrary/Modules/Payments/Services/NoPspService.cs

https://app.asana.com/0/1201394730777422/1205142033930599/f
Return NoPsp provider settings in NoPspService settings getter function to fix the following problem: 
When calling the GetProviderSettingsAsync in the NoPspService returned an empty PaymentServiceProviderSettingsModel. This caused the type to be Unknown and Title to be null.
This then goes wrong in de OrderProcessesService where the result is used to get the right PaymentServiceProviderService.

Return NoPsp provider settings in NoPspService settings getter function

---

GeeksCoreLibrary/Components/Pagination/Pagination.cs

The "HandleRequest" setting for the repeater and pagination dynamic component mentions that it impacts the TEMPLATES of that component, however the pagination code also uses it for the QUERY of the component. The repeater query code does not. This change should fix that and make the setting consistent and comply with the actual description.

Fixed inconsistency in "Handle request" content option

---

GeeksCoreLibrary/Components/OrderProcess/Services/CachedOrderProcessesService.cs

https://app.asana.com/0/1201394730777422/1204562312086552/f
Which payment methods get shown can be dependent on a multitude of different aspects like price, country, etc.
This means it shouldn't be cached.

Remove caching of payment methods of order process

---

GeeksCoreLibrary/Core/Controllers/GeoLocationController.cs
GeeksCoreLibrary/Core/Interfaces/IGeoLocationService.cs
GeeksCoreLibrary/Core/Services/GeoLocationService.cs

The `addressinfo.gcl` call didn't work anymore due to a change that was implemented by dependabot a while ago. Also fixed the naming of some methods (async methods that were missing the `Async` suffix) and added logging for errors.
[Asana ticket](https://app.asana.com/0/1201394730777422/1204914613897712)

Fixed Pro6PP API connection

---

GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

If an application that is not webbased uses the GCL it would crash during replacements because the httpcontext is null.
https://app.asana.com/0/1201027711166952/1206054275314309

Fix replacements that are dependent on the httpcontext.

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Query could get stuck on setting the variable even though the SELECT-statement gives a result within half a second. Now the ordering is passed through C#.

Fix retrieving order for parent items.

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Core/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Core/Extensions/StringExtensions.cs
GeeksCoreLibrary/Core/Models/GclSettings.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/GeeksCoreLibrary.csproj
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Databases/Interfaces/IDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Models/ColumnSettingsModel.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseHelpersService.cs
GeeksCoreLibrary/Modules/Languages/Services/CachedLanguagesService.cs
GeeksCoreLibrary/Modules/Objects/Services/CachedObjectsService.cs
GeeksCoreLibrary/Modules/Templates/Extensions/DbDataReaderExtensions.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

This changes the package for the MySQL database connections to `MySqlConnector` instead of `MySql.Data`, and updates all code accordingly. Also updated some Reader usages to use `await` instead of `try..finally`. This is done because our logs show a lot of connection errors, and they mostly seem to be because of bugs in the `MySql.Data` package.
**Pros**
* This package fixes various bugs that the `MySql.Data` package still suffers from. A full list can be found here: https://mysqlconnector.net/tutorials/migrating-from-connector-net/#fixed-bugs
* This package has better performance than the `MySql.Data` package. A benchmark can be found here: https://mysqlconnector.net/#performance
* Pretty much all code still works exactly the same. There are a few differences (the code has been updated …

Use MySqlConnector package instead of MySql.Data

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/Core/Models/GclSettings.cs

https://app.asana.com/0/1204297502076149/1206126975929265

Added GCL Setting to suppress the X-Frame-Options SAMEORIGIN header

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/Databases/Interfaces/IDocumentStoreConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/DocumentStoreConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDocumentStorageService.cs

https://app.asana.com/0/1200923549887805/1203802664624132
When the store_type is set to hybrid, the item will be created in the table without any details with published_environment set to none and added to the document store with the details.
This way saving the item van be split up into multiple phases.

Implement hybrid document store save

---

GeeksCoreLibrary/Modules/Databases/Services/DocumentStoreConnection.cs

This reverts a change made to the `DocumentStoreConnection`. The original change caused the code to skip the serialization part of the item that was to be added to the document store, but instead it caused no data to be stored at all.
[Asana ticket](https://app.asana.com/0/1200923549887805/1203802664624132)

Reverted document store connection change

---

GeeksCoreLibrary/Modules/Databases/Helpers/QueryHelpers.cs
GeeksCoreLibrary/Modules/Databases/Interfaces/IDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

Made the following changes:
* Added better support for database clusters with read-only databases. The GCL will try to automatically detect if a query contains any kind of modification that does not work on a read-only node.
* Create a new MySqlCommand everytime we execute a query. This is done because I was getting random NullReferenceExceptions when executing queries; Sometimes the Commands that we saved in memory were null for some reason. These changes fix that. This also has the side effect that it improved the performance by a lot. On a site that I tested this on, the loading of the homepage went from 1.8 seconds to 0,8 seconds, that is more than 50% increase in performance.
* Added some missing documentation in code.
Asana ticket: …

Improvements to MySqlDatabaseconnection

---

GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs
GeeksCoreLibrary/Core/Models/GclSettings.cs

Option to set the SameSite mode for cookies. This is necessary when a site runs in a iframe with a different parent domain.

Option to set the SameSite mode for cookies.

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

In the FillStringByClass method in StringReplacementService the evaluateTemplate parameter did nothing because the result of the EvaluateTemplate call wasn't used.

Use return value of evaluateTemplate in FillStringByClass

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Modules/Databases/Enums/VirtualTypes.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Databases/Models/ColumnSettingsModel.cs
GeeksCoreLibrary/Modules/Databases/Models/IndexSettingsModel.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseHelpersService.cs
GeeksCoreLibrary/Modules/Redirect/Services/RedirectService.cs

MySQL table columns can now be virtual. Added `value_as_int` and `value_as_decimal` columns to `wiser_itemdetail` and `wiser_itemlinkdetail`. Also fixed an issue with creating indexes when setting the length of the index. A few queries have also been updated to use the new columns.
Related Wiser pull request: https://github.com/happy-geeks/wiser/pull/247
Asana:
https://app.asana.com/0/29553867016121/1203457154031219
https://app.asana.com/0/29553867016121/1202994198179349

Added support for virtual columns

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

The indexes on the "value_as_int" and "value_as_decimal" columns have been removed.
Related PR: https://github.com/happy-geeks/wiser/pull/522
[Asana ticket](https://app.asana.com/0/1200346761113317/1206657052949249)

Removed virtual column indexes

---

GeeksCoreLibrary/Components/OrderProcess/Services/OrderProcessesService.cs
GeeksCoreLibrary/Modules/Payments/Interfaces/IPaymentServiceProviderServiceFactory.cs
GeeksCoreLibrary/Modules/Payments/Services/PaymentServiceProviderServiceFactory.cs

Removed interface to get PSP service instance by name string.
All OrderProcessesService calls to get a PSP service now use the type enum.
Previously there were 2 calls using the Title string and 2 calls using the Type enum.
This breaks if there is curently a client that has a PSP configured where the title and enum don't match!
Asana: https://app.asana.com/0/1205090868730163/1206175423560611

Removed interface to get PSP service instance by name string

---

GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs

Having /template.gcl?templateid=x is kinda redundant
Asana: https://app.asana.com/0/1205090868730163/1206749493060709
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206749493060709

Added support for /template.gcl?id=x

---

GeeksCoreLibrary/Components/ShoppingBasket/Interfaces/IShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/CachedShoppingBasketsService.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

https://app.asana.com/0/1151477971646641/1206533651519633/
Add optional parameter to overwrite user->basket link type. This way a different link type than the default type 5010 can be used when saving and loading a basket.

Add optional parameter to overwrite user->basket link type

---

GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Query caching for json.jcl requests did not work at all. Now it works in basic. Default caching minutes set to -1 means no caching (so backwards compatibility is not broken). Set to 0 or >0 query caching is applied for these requests. Resulting in more then 50% speed gain (depending on the query)
Add any open pull requests from other projects that are related to this pull request that should be merged along with this one. If there are none, you can simply say "none" or "N/A", or just leave this section empty.
Add a link to the Asana ticket. Note that **_ONLY_** the URL should be added, not the name of the ticket!

Disable query-caching for SQL templates when cachingminutes < 0

---

GeeksCoreLibrary/Modules/GclConverters/Services/HtmlToPdfConverterService.cs

Added default values for the pdf_can_copy (true)and pdf_can_edit (false) settings for when they are not set in a project.
Local run of the Cando configurator and requesting a configuration email. Checking the pdf received in the mail.
none
https://app.asana.com/0/1205090868730163/1206917764054482

Generated PDFs can copy by default

---

GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs

Rendering shopping basket will now also use the ExtraDataForReplacements property. It didn't do this before, so the extraData that you can enter in the `InvokeAsync` function wasn't actually used.
I needed this functionality for a new project and there I noticed that it didn't work. After I made this change, I verified that the functionality now works correctly in that project.
N/A
https://app.asana.com/0/1151477971646641/1206533651519632

Rendering shopping basket will now also use the ExtraDataForReplacements property

---

GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

When the page widgets got loaded, they were added to the list of global page widgets, but that caused the cached version of the global page widgets to be populated with the page widgets, causing every page to suddenly start loading that specific page widget. This branch fixes that by always creating a new list and populating it with both the global page widgets and the specific page widgets.
Tested loading a page that had a page widget, then loading another page to see if that other page didn't get the specific page template.
N/A
[Asana ticket](https://app.asana.com/0/1199894242406919/1207147750879799)

Fixed a caching issue with page widgets

---

GeeksCoreLibrary/Modules/GclConverters/Services/HtmlToPdfConverterService.cs

After checking whether the footer setting was empty it got the footer text from system objects and placed it in the header.
Generated a PDF from a template
N/A
No ticket.

Fix pdf settings footer being put in header.

---

GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

In the TemplateService, the logger type parameter and the xml comment on the contructor referred to the LegacyTemplatesService which is a different type. This caused some confusing logs where exceptions in new projects seemingly happened in legacy code.
I only checked whether the GCL build correctly.
N/A
No ticket

Replace references to LegacyTemplatesService type with correct type

---

GeeksCoreLibrary/Modules/GclConverters/Services/HtmlToPdfConverterService.cs

The GetHtmlToPdfSettingsAsync method gets name of the background from the item details however the image upload property, which gets used to add the backrgound image to the item, adds the image to wiser_itemfile and doesn't anything to wiser_itemdetail. This means this function then can't find the image settings.
Generated a PDF with a background image added via the image_upload field. First before the change, there was no background shown. Then with the change, background was now added.
No effect when generating a PDF with a template that did not have a background
N/A
https://app.asana.com/0/1151477971646641/1206533651519639

When getting html to pdf settings get the default background property name from system objects.

---

GeeksCoreLibrary/Modules/PostalServices/PostNL/Controllers/PostNLController.cs
GeeksCoreLibrary/Modules/PostalServices/PostNL/Interfaces/IPostNLService.cs
GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/ParcelType.cs
GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/ShippingLabelRequestModel.cs
GeeksCoreLibrary/Modules/PostalServices/PostNL/Models/ShippingLocations.cs
GeeksCoreLibrary/Modules/PostalServices/PostNL/Services/PostNLService.cs

Adds option to generate POSTNL label for mailbox parcels. This uses to product code for unsorted mail.
Potential breaking changes: The ShippingLocations enum was moved to the namespace GeeksCoreLibrary.Modules.PostalServices.PostNL.Models
When generating labels via the POSTNL API this now used a higher version of the API from v1 to v2.2. In my tests I didn't find any issues but considering it's a major version difference, I think it is at least significant enough to mention.
Generated labels with new option for mailbox parcels and standard, inspecting the response for the API to check whether the correct label type was generated and checking whether the PDF was generated correctly
N/A
https://app.asana.com/0/1201394730777422/1205247186052420/

Add support for generating mailbox parcel labels

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Account/Services/AccountsService.cs

Describe your changes
Using cookie name setting when given, so the functionality for multiple account components on one page works correctly.
Created a page with two account components and the old GCL. When 'automatical login' functionality is used, both components were logged in, while one component used a different cookie name. Run this again with a new GCL and then the problem was solved.
None
No Asana ticket

Bugfix using multiple account components on page

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

In handleCoupon setoriginal_price itemdetail to basket lines to the price value if it doesn't exist. Without this value the calculation later in this method results in a price of 0 which causes the coupon to be seen as invalid.
N/A
https://app.asana.com/0/1151477971646641/1206533651519632

Set original_price if not exists when adding coupon

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

Fixed problem that extra data query results were cached globally instead of per basket. This caused problems for projects that allow multiple baskets at once.
I have tested this with the customer were we noticed this problem.
N/A
https://app.asana.com/0/1151477971646641/1206533774168792

Fixed caching problem with baskets

---

GeeksCoreLibrary/Modules/Branches/Helpers/BranchesHelpers.cs
GeeksCoreLibrary/Modules/Branches/Models/ObjectCreatedInBranchModel.cs

Fixed problem that links were sometimes not merged when they should be. This was caused by the fact that the ID of `wiser_itemlink` is not saved in `wiser_history`, but this code assumed that it was.
I have tested these changes by making a fork database of a backup just before the moment that the original problem occurred. I then verified that I could reproduce the problem before making any changes and then tested my changes to see if they fixed the problem, which they did, and not cause new probems, which they didn't.
https://github.com/happy-geeks/wiser-task-scheduler/pull/203
https://app.asana.com/0/7257459017111/1207597501842581/1207646424960318/f

Fixed problem that links were sometimes not merged when they should be

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

Added `wiser_history` with new column `target_id` to `WiserTableDefinitions`. This is needed for being able to properly merge changes that are done in `wiser_itemdetail` tables when merging a Wiser branch. Some changes, such as changes to `language_code` and `key`, were never merged.
I tested this by making several test branches in the wiser demo database and doing lots of test merges there.
https://github.com/happy-geeks/wiser/pull/651
https://github.com/happy-geeks/wiser-task-scheduler/pull/222
https://app.asana.com/0/1205090868730163/1207370849820110

Added wiser_history with new column "target_id" to WiserTableDefinitions

---

GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseConnection.cs

The query caching in GCL adds SQL parameters to the cache key, to make sure that the same query with different parameter values would never return the same result. There was a problem with this however; if parameters were added that aren't used in that particular query, then that would also cause multiple cache entries, even though that's not necessary. This caused an issue that queries were not cached enough, because there would often be parameters added to the connection that are needed for other queries. This PR fixes that issue by only using parameters that are actually used in the query that is being cached.
By running the GCL in a random webshop and debugging the code to see if the queries get cached better now.
N/A
No Asana ticket. This issue was found …

Improved query caching

---

GeeksCoreLibrary/Core/Models/GclSettings.cs

The configurator cache setting has no purpose anymore, so it's been removed.
Tested if the project still compiles. The setting wasn't actually used anymore, so there's nothing to test.
N/A
CON-286

Removed configurator cache setting

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/Core/Middlewares/AddCacheHeaderValueMiddleware.cs
GeeksCoreLibrary/Core/Models/CacheControlRuleSettingsModel.cs
GeeksCoreLibrary/Core/Models/GclSettings.cs

Add middleware for configuring cache-control header values for file paths via appsettings.
Set the following appsettings in a development web project:
```
"GCL": {
...
"CacheControlRules": [
{
"filePath" :  "//scripts/jjl-core.min.js", <-- don't ask me why the web project is requesting "//"
"headerValue":  "max-age=12345"
}
]
}
```
And then checked within the chrome devtools in the gordijnen vadainbv configurator, in which the given filePath is being requested, is the only one with a Source-Control header with value max-age=12345.
Given Cache-Control rule:
Other JS requests without Cache-Control rules:
N/A
https://app.asana.com/0/1199894242406919/1207022541266964

Cache-Control middleware

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs

In the startup functions in the GCL a NullReferenceException would occur if no logger is set when updating tables failed.
Tried to run the project that was affected by this bug again after the fix and confirmed it could start up without issues.
N/A
No Asana ticket, ran into this issue while trying to debug a project.

Fixed NRE for missing logger

---

GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

Removed virtual columns from table definitions so that they are no longer added to (new) databases, we don't use them anymore.
There is nothing to test here.
https://github.com/happy-geeks/wiser/pull/709
https://app.asana.com/0/29553867016121/1207008950317958

Removed virtual columns from wiser_itemdetail and wiser_itemlinkdetail in table definations.

---

GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseHelpersService.cs

The property was set on the decorator while the actual service remained unset. This passes any property values from the decorator to the actual service.
Tested by checking and updating a table passed through the extra Wiser table definitions while using the cache decorator.
N/A
N/A

Pass property of cached service to actual service

---

GeeksCoreLibrary/Components/OrderProcess/Models/OrderProcessCheckoutSettingsModel.cs

In place of the {Pattern} replacement the GCL would try to add `pattern='{field.Pattern}'`. Because of the HTML encoding the single quotes would get replaced. Then there would be double quotes placed around that resulting it to look like: `pattern="'{field.Pattern}'"`.
Added pattern into a WiserFormField type that was used in an orderprocess. Above was the result. Added the :Raw formatter and the regex worked correctly again.
N/A
https://app.asana.com/0/1201394730777422/1208257594052329/f

Don't use html encoding for regex pattern attribute in order processservice

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Skip cache in 2 queries in save item detail method.
First is a query that checks whether a detail exists, 
second is an insert of the detail using the GetAsync. Since this is an insert it should also use the writing connection.
Got duplicate key errors when debugging an issue with caching enabled, after adding this change the errors disappeared.
N/A
https://app.asana.com/0/1151477971646641/1208083523017881

Skip cache when saving item detail

---

GeeksCoreLibrary/Modules/Templates/Interfaces/ITemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyCachedTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

When a user was logged in, went to a page you can only see while logged in and then logged out he would still be able to see the page. This was because the result of the permissions check got cached. These changes fixes this by adding the result of the permissions check to the caching key and seperately checking permissions in the CachedTemplateService
On a website where most pages contained templates that required user login. I navigated through several pages, and logged in and out several times. This was done locally with settings caching duration set to 1 hour and environment on acceptance.
N/A
https://app.asana.com/0/1151477971646641/1208083523017881/f

Fix template permissions bug when caching is active

---

GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

Wiser items files was cached using the filesystem using the filename and also using the query cache. This causes issues for functionalitity where the file can change. For example when the user can add and change an image.
Tested it with functionality where the end user could change change an image to a different one. Before the change the cached image would get shown after updating the image, after the change it would correctly update.
No slowdown in image loading was detected because the files are still being cached using the filesystem.
N/A
https://app.asana.com/0/1151477971646641/1208464225403868/f

Skip cache when getting item files

---

GeeksCoreLibrary/Modules/Redirect/Middlewares/RedirectMiddleWare.cs

When using the redirect module to redirect to a relative url there would be an UriFormat exception when doing the redirect.
This fixes that by getting the baseUrl of the request and turning the relative url in an absolute url.
This allows redirects to work correctly across different environments.
Made two redirect rules. One with an absolute newUrl and one with a relative newUrl and tested wether both redirects worked correctly after the change.
N/A
https://app.asana.com/0/1205090868730163/1208538439984826/f

Fix redirect to relative uri

---

GeeksCoreLibrary/Modules/ItemFiles/Controllers/ItemFilesController.cs
GeeksCoreLibrary/Modules/ItemFiles/Interfaces/IItemFilesService.cs
GeeksCoreLibrary/Modules/ItemFiles/Middlewares/WiserItemFilesMiddleware.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/CachedItemFilesService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

Allows for an image to be retrieved by file name. This is meant for a collection of images that belong to a single item and property name.
Used a debug build to determine it would retrieve an image by file name correctly, and that it would return a 404 status code if an image couldn't be found.
N/A
CON-601

Get item file image by filename

---

GeeksCoreLibrary/Core/Models/SshSettings.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

Added option to set the private key as a byte array instead of a file path.
Tested if the SSH connection still worked if the bytes version was used instead of the file path version.
N/A
CON-672

SSH settings private key bytes

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
GeeksCoreLibrary/Core/Helpers/HttpContextHelpers.cs

Fixed problem that if we log in a user and then request the data of that user within the same request, we would get an empty result. This was because the login cookie was only added to the response, not to the current request.
This went wrong with a customer website that uses the OCI standard for placing orders. They do POST request to certain endpoints, with login credentials and an cXML that contains the order that they want to place. We need to log them in and then immediately get the user ID from the cookie and use that to place the order for that user. This went wrong, because we couldn't read the cookie at that point.
This was tested via the same customer by simulating OCI order requests via PostMan. I was able to reproduce the issue and then verify …

Fixed problem with logging in users and immediately needing the cookie

---

GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs

Makes the mapping of the bcc and cc strings to arrays more robust by trimming the values. Otherwise mail can be rejected due to having extra spaces around the values.
Sent a mail
N/A
N/A

Trim bcc and cc adresses when creating CommunicationReceiverModel

---

GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs

In an earlier PR the wrong bitwise operator was used which resulted in StringSplitOptions functionality being set to StringSplitOptions .None. This fixes that.
I also found another place where this mistake was made and then went through all usages of Split to see wether it should be trimmed and empty entries removed.
Changed set bcc settings on test account on a GCL site to a value that would go wrong before and had it send a mail.
Corrects mistake in https://github.com/happy-geeks/geeks-core-library/pull/693
N/A

Fix triming and removing empty entries for bcc en cc when setting up an e-mail

---

GeeksCoreLibrary/Modules/Amazon/Services/AmazonS3Service.cs

It's now also possible to create an `AmazonS3Client` with only a region, or without any parameters at all. This is useful for websites hosted on AWS that authenticate themselves through AWS services internally.
Checked if leaving out the access and secret keys would still create a client with only a region, and if leaving out the AWS settings completely that it would still create a client without credentials AND region.
N/A
CON-672

Amazon S3 auth changes

---

GeeksCoreLibrary/Modules/HealthChecks/Services/WtsHealthService.cs

The WTS healthcheck should always use the latest data but the result of the query to get the current status of the configurations in the WTS got cached.
Used the WTS healthcheck endpoint `/health/wts/`
N/A
https://app.asana.com/0/1201394730777422/1206033897144715/f

Disable cache for configuration query in WTS health check

---

GeeksCoreLibrary/Modules/Communication/Services/CommunicationsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

Improvement for downloading files from external URLs. We now check if the HTTP response status is actually a 200, before we load the byte array. Otherwise we were constantly downloading 404/500 paqes and trying to save that as an image.
By testing if valid responses still work and if 404 responses are no longer being loaded into the byte array.
N/A
N/A

Added some error handling when downloading external files

---

GeeksCoreLibrary/Components/Account/Account.cs
GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/Databases/Helpers/MySqlHelpers.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

A while ago, a change was made in the GCL to always throw a custom new `GclQueryException` when an error occurs while executing an MySQL query. This caused error handling based on `MySqlException` to no longer work. I fixed this now so that the error handling works with `GclQueryException`.
By simulating exceptions and testing if the error handling works.
https://app.asana.com/0/1151477971646641/1208880798391869

Fixed deadlock error handling

---

GeeksCoreLibrary/Core/Models/WiserItemFileModel.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Controllers/ItemFilesController.cs
GeeksCoreLibrary/Modules/ItemFiles/Middlewares/WiserItemFilesMiddleware.cs

Added "protected" property to WiserItemFile model, so "protected" can be used when working with item files with the WiserItemsService.  Added option to load files and images with encrypted id, so loading protected files and images is possible with 'friendly' URL's.
N/A
https://app.asana.com/0/29553867016121/1209089391010914

Added "protected" property to the WiserItemFile model and added option to load protected files and images on 'friendly' URL's

---

GeeksCoreLibrary.Tests/Core/Services/WiserItemsServiceTests.cs
GeeksCoreLibrary/Core/Models/RoleModel.cs
GeeksCoreLibrary/Core/Services/RolesService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

New validation added to give user's permissions based on a list of ip addresses. A new step with an input field has been added when you add a role to an user, there we can set the allowed ip addresses.
This was tested on an internal project using the GCL locally together with Wiser. New test user's were created and tested with allowed and not allowed ip addresses.
N/A
https://app.asana.com/0/1206726301569963/1206726303952398/f

New IP addresses validation

---

GeeksCoreLibrary/Components/Account/Services/AccountsService.cs
GeeksCoreLibrary/Core/Models/RoleModel.cs
GeeksCoreLibrary/Core/Services/RolesService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Recently new functionality was added to connect roles to users based on their IP address. This caused the function `RolesService.GetRolesAsync` to return way too many results, because a JOIN was added in the wrong place.
I fixed this by removing the JOIN in that query and changing the correct query to get the roles.
N/A
N/A

Fixed problem that the RolesService.GetRolesAsync function returned way too many rows since the latest change.

---

GeeksCoreLibrary/Modules/GclReplacements/Enums/UnsafeSources.cs
GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

A small update to the "unsafe source" functionality for the replacements so it knows what the exact source is for additional control over what kind of protection should be added (like protection against XSS). For now, only the HttpRequest is added as an unsafe source, which means that the values will be URL-encoded.
Tested to see if the additional protection fixes a few XSS vulnerabilities that were found.
N/A
CON-918

Update for "unsafe source" replacements

---

GeeksCoreLibrary/Components/ShoppingBasket/Models/Constants.cs
GeeksCoreLibrary/Components/ShoppingBasket/Models/VatRule.cs
GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

When getting the vatrules from the database when the a vatrule had a vatratepercentage of 0, the code assumed this meant no vateratepercentage was given and changed it to the default of 21 this meant vatrates of 0 didn't work.
Opened a basket in which multiple vatrates were used including 0. The price was incorrect before the change and it was correct after.
N/A
https://app.asana.com/0/1151477971646641/1209115089987721

Fix 0 vat rate percentage not being possible to set

---

GeeksCoreLibrary/Components/ShoppingBasket/ShoppingBasket.cs
GeeksCoreLibrary/Core/Helpers/FileSystemHelpers.cs
GeeksCoreLibrary/Core/Models/Constants.cs
GeeksCoreLibrary/Core/Services/CacheService.cs
GeeksCoreLibrary/Modules/Barcodes/Services/CachedBarcodesService.cs
GeeksCoreLibrary/Modules/GclConverters/Services/HtmlToPdfConverterService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/CachedItemFilesService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

There was a problem that background images in PDFs did not work anymore. This was caused by moving the FilesCache directory outside of the wwwroot, which made them no longer publicly available. That also meant that the PDF converted could no longer access the files.
To fix this, I created a new `PublicFiles` directory in the `wwwroot`, with corresponding helper functions for using this new directory. The HTML to PDF converted now saves the background images in this new directory, which fixes the problem.
I also renamed other helper functions that had strange names, so that the names make more sense.
I tested this in Wiser, by generating PDF files and testing if they have background images.
N/A
https://app.asana.com/0/1182779092805226/1209312570707874

Fixed problem that background images in PDFs no longer worked

---

GeeksCoreLibrary/Components/ShoppingBasket/Services/ShoppingBasketsService.cs

When the basket had a detail called `price` this would get used when doing the replacements in the basket instead of the value calculated by the ShoppingBasketService. To fix this those details are removed from the replacement data before calling doReplacements
Used the GenerateHtmlFromBasket function in a basket with a detail called price to generate a PDF.
N/A
https://app.asana.com/0/1151477971646641/1209151457501068
https://app.asana.com/0/1151477971646641/1209138204185196

Fix bug with price basket detail not being handled well in basket replacements

---

GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs

Recently it was added that replacements from unsafe sources would get url encoded. This caused problems in some queries were for example a `,` would get changed into `%2c`. Causing those queries to no longer produce the correct results.
For queries replacements are already done using sql parameters so further sanisation isn't needed in this context.
Ran a query in which comma seperated values were used. After the fix the correct results were returned.
N/A
https://app.asana.com/0/1201394730777422/1209329181412568

Skip stripping and encoding sql parameters.

---

GeeksCoreLibrary/Modules/Objects/Services/CachedObjectsService.cs
GeeksCoreLibrary/Modules/Objects/Services/ObjectsService.cs

Easy objects were loaded with keys that were `null` to build the cache. If an invalid key was present the GCL would crash and prevent any page from being loaded.
During branch merges this can occur if an object has been added on both the branch as main database before the merge preventing the system to write the key to the main database.
Tested by adding an item to `easy_objects` with the key as `null` and checked if the website launched after the fix.
N/A
https://app.asana.com/0/1205090868730163/1209377447755702

Fix easy objects from being loaded with no key

---

GeeksCoreLibrary/Modules/Templates/Controllers/TemplatesController.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs

Execute preload query before HTML DoReplacesAsync & Add HTML only check for GetRenderedTemplateAsync.
* Fixes bug in which the GCL also does replacements on JS, which it shouldnt.
* Fixes GCL templates caching bug in which pre load queries got executed after the doReplacesAsync which caused unresolved template variables
Tested an HTML template in a local project that uses a preload query, making it accessible both within the template and on dynamic content pages referencing the template variable.
Additionally, tested a local configurator project, which now opens successfully after being able to resolve the template variables.
none
https://app.asana.com/0/1205090868730163/1209339034569767
https://app.asana.com/0/1205090868730163/1203021850171653

Execute preload query before HTML DoReplacesAsync & Add HTML only check for GetRenderedTemplateAsync

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Updating an item with a custom query didn't work anymore due to the entity type always being required. Setting an entity type, however, causes the custom query to not be used. This checks if entity type is set before deciding to use it and falls back to the item's entity type if it isn't set.
Used a debug build and tested in Wiser if saving an item with a combobox and multiselect that use custom queries worked as intended, and saved the links as exepected.
N/A
[Asana ticket](https://app.asana.com/0/1205090868730163/1207511625868424)

Fix for entity type always being required

---

GeeksCoreLibrary/Core/Interfaces/IFileCacheService.cs
GeeksCoreLibrary/Core/Services/FileCacheService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/CachedItemFilesService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedPagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs

Adds a FileCacheService that can be used for concurrency and uses this for the caching of templates, dynamic content and item files. This helps to minimize the amount of IOExceptions that can currently fill up our logs, often getting in the way when trying to find issues of other types.
At the core of the implementation is a ConcurrentDictionary that is used to track to which file is currently being written.
The FileCacheService itself was first tested in a console application in which a ParallelEnumerable was used create 2 files in multiple threads. First simply writing the file to make sure I consistently got file access exceptions and then adding the Service.
After that I added the implementation to the GCL and used the library in a project which used a …

File cache concurrency

---

GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs

Use Uri.EscapeDataString for encoding in ReplacementsMediator.cs.
This is the same used by the StringReplacementsExtensions. This way it is possible to reverse the encoding by using the UrlDecode formatter.
The difference is that HttpUtility.UrlEncode encoded spaces differently (into pluses) and Uri.UnescapeDataString doesn't reverse this.
Tested a template in which values were url encoded due to be gotten from a request (a webform). Before the change spaces were not being unencoded despite the use of UrlDecode formatter, after the change I saw spaces as expected.
N/A
https://app.asana.com/0/1151477971646641/1209483497653720
https://app.asana.com/0/1151477971646641/1209483559517718

Use Uri.EscapeDataString for encoding

---

GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

Fixed bug where pre-load query was not executed in HTML templates when being called via a [include]. Also merged some duplicate code together.
Used template veriables in combination with several HTML templates with includes and different preload queries within a test project.
none
https://app.asana.com/0/1205090868730163/1203064463742150

Bugfix where pre load query was not executed in HTML includes

---

GeeksCoreLibrary/Core/Services/HttpClientService.cs

I noticed that our `HttpClientService` would always use HTTP version 1.1. This version is very old, we have version 3 at the moment. I updated the default `HttpClient` settings to automatically use HTTP 3 when the server supports it, otherwise it will use the highest version that the server does support.
By doing some HTTP calls to servers that I know support HTTP 2 and HTTP 3 and some that don't, to test if the fallback and everything works.
N/A
No Asana ticket, noticed this myself and was a small fix.

Added HTTP 2 and 3 support to `HttpClientService`

---

GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Interfaces/IStringReplacementsService.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/ReplacementsMediator.cs
GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs
GeeksCoreLibrary/Modules/Templates/Services/LegacyTemplatesService.cs
GeeksCoreLibrary/Modules/Templates/Services/TemplatesService.cs

When checking PR https://github.com/happy-geeks/geeks-core-library/pull/802, I noticed that we have a very ugly way of parsing the query string from includes. But this was not the fault of the creator of that PR, because he just moved the code, it already was like that. So I fixed it myself in this PR.
I made a test controller in a test project to do some tests if the includes still work properly after my changes.
https://github.com/happy-geeks/geeks-core-library/pull/802
N/A

Improved query string parsing by using .NET functions instead of custom code with Split().

---

GeeksCoreLibrary/Core/Helpers/XmlHelpers.cs

Add option to enable DTD processing. Sets the DtdProcessing to DtdProcessing if the passed boolean is true. The default of DtdProcessing is prohibited which gives an exception when a DTD is present. This is done for security reasons.
This change adds support for DTD if the XML comes from a trusted source and otherwise ignores the DTD.
Passed an XML with a DTD into the method. Before the change I got an exception, after the change it went through without a problem.
N/A
https://app.asana.com/1/5038780173035/project/1151477971646641/task/1209639471354164

Add option to enable DTD processing to DeserializeXml

---

GeeksCoreLibrary/Modules/Templates/Services/CachedPagesService.cs
GeeksCoreLibrary/Modules/Templates/Services/PagesService.cs

The call to `GetRenderedTemplateAsync` in the `CachedPagesService` didn't pass the `useAbsoluteImageUrls` and `removeSvgUrlsFromIcons` parameters, causing that functionality to no longer work unless the template has caching enabled.
Used a debug build and tested my changes in a situation where I knew there was a problem and confirmed that these changes fixed the issue.
N/A
[Asana ticket](https://app.asana.com/1/5038780173035/project/1200346761113317/task/1209666684409090)

Fixed call to `GetRenderedTemplateAsync`

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

This is a fix to standardize file names and also to deal with unsupported file extensions. In the file names case we were getting an error while caching them due to some files being saved in the database with more characters than the system allows.
Using a GCL test template and Wiser Demo, files with the previously unsupported extensions were uploaded and the names were checked.
N/A
https://app.asana.com/0/1205090868730163/1209653638314379/f

Fixing error logs regarding big file names and file extensions

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/CachedItemFilesService.cs

This change is a fix to a previous one that was made wrongly. Previously the change was made standardizing the file names in the wrong database, this fix now removes that and adds some details to the caching functionallity, where it was supposed to be in the first place.
Locally running the GCL with an internal project and checking the cached files.
N/A
https://app.asana.com/0/1205090868730163/1209653638314379/f

Fixing previous edition on the file name saving

---

GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

Fixed a regression that caused looking up images by file name to no longer work unless you used a high index/file number.
Tested to see if my fixes allowed to look up images by file name correctly again, and that image lookups using other lookup types still worked correctly as well.
None
CON-1454

Fixed regression in image lookup by file name

---

GeeksCoreLibrary/Components/OrderProcess/Models/OrderProcessCheckoutSettingsModel.cs
GeeksCoreLibrary/Components/OrderProcess/Models/OrderProcessCmsSettingsModel.cs
GeeksCoreLibrary/Components/OrderProcess/OrderProcess.cs

The chosen payment method would not be remembered from the point of view of the user when going back to the step in which the paymentMethod was chosen. Requiring them to re-select the payment method. This fixes that be selecting the payment method recorded in the basket.
Stepped through checkout process. Trying different selections.
N/A
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1203956850515021

Enhance payment method rendering to include selected method state

---

GeeksCoreLibrary/Core/Extensions/ConfigurationServiceCollectionExtensions.cs
GeeksCoreLibrary/Modules/Redirect/Middlewares/RedirectMiddleWare.cs

Fixed problem that files with encrypted IDs didn't work if the option is enabled for redirecting all pages to lower case URLs, because that would change the encrypted ID to a lower case value, which would make it invalid.
This is fixed by changing the order of some middlewares.
By opening files with encrypted ids.
N/A
https://app.asana.com/1/5038780173035/project/1201394730777422/task/1210022298302285

Fixed problem that files with encrypted IDs didn't always work

---

GeeksCoreLibrary/Core/Models/WiserTableNames.cs
GeeksCoreLibrary/Modules/Branches/Helpers/BranchesHelpers.cs
GeeksCoreLibrary/Modules/Branches/Models/MergeBranchSettingsModel.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs

I added a lot of logging to the WTS to log everything it does and decides when mering a Wiser branch. This pull request in the GCL adds the new table where these logs are saved and one minor bugfix in another shared method, that I found while checking/testing the logs.
I tested this on Wiser demo by doing a whole lot of test merges and then going through all the logs to see if they are correct.
https://github.com/happy-geeks/wiser-task-scheduler/pull/312
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1209921173095221

Added new log table for logging the merging of Wiser branches

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs
GeeksCoreLibrary/Modules/ItemFiles/Helpers/PrecompiledRegexes.cs
GeeksCoreLibrary/Modules/ItemFiles/Middlewares/WiserItemFilesMiddleware.cs

Turn the regexes used to match file and image urls into generated regexes. This is an performance improvement.
These were missed when doing https://github.com/happy-geeks/geeks-core-library/pull/834 because these didn't have RegexOption.Compiled but there is no reason to leave these uncompiled.
Opened a website and checked whether all images where shown correctly and then manually tried several file urls.
N/A
N/A

Add precompiled regexes for image and file URL matching

---

GeeksCoreLibrary/Core/Interfaces/IWiserItemsService.cs
GeeksCoreLibrary/Core/Services/CachedWiserItemsService.cs
GeeksCoreLibrary/Core/Services/LinkTypesService.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

If the source and destination items use different table prefixes, then it would not find the correct link settings and not use `parent_item_id`. This happened most often with link type `1`, because that one is used for multiple entities.
By creating new items with a parent id and checking if correct links are created.
https://github.com/happy-geeks/wiser/pull/916
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1206957555415824

Fixed problem that creating items with a parentId, would not link them correctly in certain situations.

---

GeeksCoreLibrary/Core/Models/WiserItemModel.cs
GeeksCoreLibrary/Core/Services/WiserItemsService.cs

When an item has been created on a link the link ID is passed along. This will be used in Wiser to use it correctly for the API response.
Tested by creating a new item and checking if the value is set when creating on a link without a parent and that it stays empty when creating on a parent item ID link.
N/A
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1205529420472876

Pass link ID of new created item back.

---

GeeksCoreLibrary.Tests/Modules/ItemFiles/Services/ItemFilesServiceTests.cs
GeeksCoreLibrary/Modules/ItemFiles/Services/ItemFilesService.cs

Two methods for retrieving files from `wiser_itemfile` didn't pass the `propertyName` parameter to the `GetParsedFileAsync` method causing those methods to always throw an exception.
Used a debug build and unit tests to confirm that the methods no longer throw an exception due to the `propertyName` parameter being `null`.
None.
[Asana ticket](https://app.asana.com/1/5038780173035/project/29553867016121/task/1209959062320600)

Fixes for retrieving Wiser files

---

GeeksCoreLibrary/Core/Models/WiserTableNames.cs
GeeksCoreLibrary/Core/Services/EntityTypesService.cs
GeeksCoreLibrary/Modules/Branches/Helpers/BranchesHelpers.cs
GeeksCoreLibrary/Modules/Databases/Helpers/WiserTableDefinitions.cs
GeeksCoreLibrary/Modules/Databases/Interfaces/IDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Interfaces/IDatabaseHelpersService.cs
GeeksCoreLibrary/Modules/Databases/Models/IndexColumnModel.cs
GeeksCoreLibrary/Modules/Databases/Models/IndexSettingsModel.cs
GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseHelpersService.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseHelpersService.cs

Added some new functionality for working with databases and improved some existing functionality:
- Added new function `ExecuteScalarAsync` to `IDatabaseConnection`, this function is very useful when doing queries that return only a single row with a single column, then you don't have to store that in a `DataTable` first. This is a minor breaking change, because if other projects have their own implementation for `IDatabaseConnection`, they will have to also add an implementation for this new method. As far as I know, only Wiser does this and I already have a commit ready to implement it there.
- Added new functions to `IDatabaseHelpersService` for getting a list of indexes of one or more database tables.
- Added new functions to `IDatabaseHelpersService` for getting a list of columns of …

Added some new functionality for working with databases and improved some existing functionality

---

GeeksCoreLibrary/Modules/Templates/Services/CachedTemplatesService.cs

In changed code the reference to the cached object was returned causing modifications to be appleid to the cached value. Now a clone is correctly again returned.
Tested by validating the cached value is correct instead of a modified one after the first return.
N/A
1709

Return clones of the cached values

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

Allow permissions for items to be applied to specific entities. This fixes the problem that if permissions are set this is applied to entities in wiser_item and any prefix table with the same ID.
For backwards compatibility, if no entity type is provided with the permission it still applies to all items with the same ID.
Tested by adding a permission for an item and validated the correct behavior if no entity type has been provided, if the entity type of the item in `wiser_item` was provided and the entity type of the item in the prefix table.
https://github.com/happy-geeks/wiser/pull/922
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1209869916047907

Allow permissions for items to be set to specific entity

---

GeeksCoreLibrary/Components/Repeater/Models/Constants.cs
GeeksCoreLibrary/Components/Repeater/Models/RepeaterRepeaterSettingsModel.cs
GeeksCoreLibrary/Components/Repeater/Models/RepeaterTemplateModel.cs
GeeksCoreLibrary/Components/Repeater/Repeater.cs

Added a new placeholder / replacement `{SubLayer}`. This can be used in the `ItemTemplate` of any layer in the Repeater settings. With this you can render the next layer in a specific location. Before, the Repeater would always render the next layer immediately after the `ItemTemplate`, which meant you couldn't load the next layer inside another HTML-element. With this change you can.
Besides that, I also fixed a bug that caused the `NoDataTemplate` to not always be rendered.
Lastly, I moved some hard-coded string to constants and fixed a typo in a property name.
Tested this in a new project that I'm working on, where I need this functionality to not have to set up the Repeater in a very illogical and confusing way.
N/A
There is no specific Asana ticket for …

Improvements for the Repeater component.

---

GeeksCoreLibrary/Modules/Databases/Interfaces/IDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/CachedDatabaseConnection.cs
GeeksCoreLibrary/Modules/Databases/Services/MySqlDatabaseConnection.cs

Added the function `ReplaceVariablesInQueryForDebugging` to `IDatabaseConnection` for a quicker and easier way to debug queries. You can just call this method in the debugger to get a query that you can directly execute in other software, such as Navicat. Then you don't need to replace all the variables in the query manually anymore, before you can execute it.
Obviously, this function should never be called in production code. So to prevent that, I added an `#if DEBUG` statement around it.
I was kinda tired of always having to replace a whole bunch of variables in queries to be able to test the query in Navicat. Then I got the idea to make a function for this, so I did that and immediately used/tested it. It worked fine for the queries that I needed it for. …

Added debug function for queries

---

GeeksCoreLibrary/Modules/GclReplacements/Services/StringReplacementsService.cs

Old code checked the input type if it could find the requested child. This is useless because the input is always a JToken based on the original model.
Fetim Retailplatform has a PDF template that uses {child.property} replacements. This fix makes that work.
Also tested with {template.blabla} in templates that have a pre-load query. Those still work.
n/a
none

Changed string replacements to work with (always used) JToken input

---

GeeksCoreLibrary/Core/Services/WiserItemsService.cs

When an exception was thrown handling a query while deleting an item, it would only check if no new transaction needed to be made before performing a rollback. Since the transaction was already active the method didn't start the transaction itself and should not close it. This is done everywhere else in the class.
This caused problems that a rollback was performed but the above lying logic was still thinking a transaction was present and started to execute queries outside of a transaction.
Tested by using the WTS branch merge to delete an item and then insert one while forcing an sql exception during deletion. This caused the item to not be deleted due to the rollback but still insert the new item. After extending the check the rollback was not performed and …

Extend check to include if the transaction was started outside the function
